/* Booking page strings */
window.I18N = window.I18N || { fr: {}, de: {}, en: {} };

Object.assign(window.I18N.fr, {
  'rv.hero.eyebrow': 'Prise de rendez-vous',
  'rv.hero.title': 'Réservez votre séance.',
  'rv.hero.text': 'Choisissez le soin, le lieu et le créneau qui vous conviennent — quelques instants suffisent.',

  'rv.step.1': 'Le soin',
  'rv.step.2': 'Lieu & durée',
  'rv.step.3': 'Date & heure',
  'rv.step.4': 'Coordonnées',
  'rv.step.5': 'Confirmation',

  'rv.s1.title': 'Quel soin souhaitez-vous ?',
  'rv.s1.sub': 'Sélectionnez une prestation pour commencer.',
  'rv.cat.massage': 'Massages',
  'rv.cat.drainage': 'Drainage lymphatique',
  'rv.cat.yoga': 'Yoga',

  'rv.s2.title': 'Où et combien de temps ?',
  'rv.s2.loc': 'Lieu de la séance',
  'rv.s2.dur': 'Durée',
  'rv.s2.option': 'Option',
  'rv.min': 'min',
  'rv.h': 'h',

  'rv.s3.title': 'Choisissez votre créneau',
  'rv.s3.sub': 'Disponibilités à',
  'rv.morning': 'Matin',
  'rv.afternoon': 'Après-midi',
  'rv.evening': 'Soir',
  'rv.noslots': 'Complet ce jour-là — essayez une autre date.',
  'rv.pickday': 'Sélectionnez un jour pour voir les créneaux.',
  'rv.alert.inline': 'Aucune date ne convient ? Être alerté(e) des nouveaux créneaux',
  'rv.more': 'Voir plus de dates',

  'rv.s4.title': 'Vos coordonnées',
  'rv.s4.sub': 'Pour confirmer et vous envoyer les détails.',
  'rv.f.first': 'Prénom',
  'rv.f.last': 'Nom',
  'rv.f.email': 'E-mail',
  'rv.f.phone': 'Téléphone',
  'rv.f.notes': 'Un mot pour Eloïse (optionnel)',
  'rv.f.notes.ph': 'Une attention, une zone à soulager, une première fois…',
  'rv.f.consent': 'J’accepte d’être recontactée au sujet de ce rendez-vous.',
  'rv.req': 'Ce champ est requis',
  'rv.req.email': 'Adresse e-mail non valide',

  'rv.pack.cat': 'Offres & packs',
  'rv.pack.offerLabel': '{label} — {price}€ au lieu de {regular}€',
  'rv.pack.note': 'Cette offre sera à valider avec Eloïse — le règlement se fait sur place.',
  'rv.pack.short': 'Offre',

  'rv.promo.label': 'Code promo',
  'rv.promo.ph': 'Ex. MERCI-4F2K',
  'rv.promo.apply': 'Appliquer',
  'rv.promo.applied': 'Code appliqué : -{percent}%',
  'rv.promo.free': 'Code appliqué : séance offerte',
  'rv.promo.invalid': 'Code invalide.',
  'rv.promo.used': 'Ce code a déjà été utilisé.',

  'rv.summary': 'Récapitulatif',
  'rv.sum.service': 'Soin',
  'rv.sum.loc': 'Lieu',
  'rv.sum.when': 'Date',
  'rv.sum.duration': 'Durée',
  'rv.sum.total': 'Total estimé',
  'rv.sum.discount': 'Réduction',
  'rv.sum.empty': 'À compléter',

  'rv.back': 'Retour',
  'rv.next': 'Continuer',
  'rv.confirm': 'Confirmer le rendez-vous',

  'rv.done.title': 'Demande envoyée !',
  'rv.done.text': 'Votre demande de rendez-vous a bien été transmise à Eloïse. Vous recevrez une confirmation par e-mail sous 24 h.',
  'rv.done.again': 'Faire une autre réservation',
  'rv.done.note': 'Démonstration — aucun paiement n’est demandé en ligne. Le règlement se fait sur place.',
  'rv.done.cal': 'Ajouter à mon agenda',

  'rv.gift.badge': 'Carte-cadeau',
  'rv.gift.note': 'Vous offrez cette séance. Indiquez vos coordonnées : la carte-cadeau vous sera envoyée.',

  // Alerts
  'rv.alert.eyebrow': 'Alertes créneaux',
  'rv.alert.title': 'Soyez prévenu(e) dès qu’un créneau s’ouvre.',
  'rv.alert.text': 'Ciblez un ou plusieurs lieux : je vous écris dès que de nouvelles disponibilités sont ajoutées à mon agenda.',
  'rv.alert.loc': 'Lieux à surveiller',
  'rv.alert.email': 'Votre e-mail',
  'rv.alert.freq': 'Fréquence',
  'rv.alert.freq.instant': 'À chaque nouveau créneau',
  'rv.alert.freq.weekly': 'Un résumé par semaine',
  'rv.alert.submit': 'Activer mes alertes',
  'rv.alert.done.title': 'Alertes activées',
  'rv.alert.done.text': 'C’est noté. Je vous préviens dès qu’un créneau s’ouvre pour :',
  'rv.alert.done.again': 'Modifier mes alertes',
  'rv.alert.pickloc': 'Choisissez au moins un lieu.',
});

Object.assign(window.I18N.de, {
  'rv.hero.eyebrow': 'Terminbuchung',
  'rv.hero.title': 'Buchen Sie Ihre Sitzung.',
  'rv.hero.text': 'Wählen Sie Behandlung, Ort und passenden Termin — in wenigen Augenblicken erledigt.',

  'rv.step.1': 'Behandlung',
  'rv.step.2': 'Ort & Dauer',
  'rv.step.3': 'Datum & Zeit',
  'rv.step.4': 'Kontaktdaten',
  'rv.step.5': 'Bestätigung',

  'rv.pack.cat': 'Angebote & Pakete',
  'rv.pack.offerLabel': '{label} — {price}€ statt {regular}€',
  'rv.pack.note': 'Dieses Angebot wird mit Eloïse vor Ort bestätigt — die Zahlung erfolgt vor Ort.',
  'rv.pack.short': 'Angebot',
  'rv.sum.discount': 'Rabatt',

  'rv.s1.title': 'Welche Behandlung wünschen Sie?',
  'rv.s1.sub': 'Wählen Sie eine Leistung, um zu beginnen.',
  'rv.cat.massage': 'Massagen',
  'rv.cat.drainage': 'Lymphdrainage',
  'rv.cat.yoga': 'Yoga',

  'rv.s2.title': 'Wo und wie lange?',
  'rv.s2.loc': 'Ort der Sitzung',
  'rv.s2.dur': 'Dauer',
  'rv.s2.option': 'Option',
  'rv.min': 'Min',
  'rv.h': 'Std',

  'rv.s3.title': 'Wählen Sie Ihren Termin',
  'rv.s3.sub': 'Verfügbarkeit in',
  'rv.morning': 'Vormittag',
  'rv.afternoon': 'Nachmittag',
  'rv.evening': 'Abend',
  'rv.noslots': 'An diesem Tag ausgebucht — bitte anderes Datum wählen.',
  'rv.pickday': 'Wählen Sie einen Tag, um die Termine zu sehen.',
  'rv.alert.inline': 'Kein passendes Datum? Über neue Termine benachrichtigen lassen',
  'rv.more': 'Weitere Tage anzeigen',

  'rv.s4.title': 'Ihre Kontaktdaten',
  'rv.s4.sub': 'Zur Bestätigung und für die Details.',
  'rv.f.first': 'Vorname',
  'rv.f.last': 'Nachname',
  'rv.f.email': 'E-Mail',
  'rv.f.phone': 'Telefon',
  'rv.f.notes': 'Eine Nachricht an Eloïse (optional)',
  'rv.f.notes.ph': 'Ein Hinweis, eine zu lösende Stelle, das erste Mal…',
  'rv.f.consent': 'Ich bin einverstanden, zu diesem Termin kontaktiert zu werden.',
  'rv.req': 'Dieses Feld ist erforderlich',
  'rv.req.email': 'Ungültige E-Mail-Adresse',

  'rv.summary': 'Übersicht',
  'rv.sum.service': 'Behandlung',
  'rv.sum.loc': 'Ort',
  'rv.sum.when': 'Datum',
  'rv.sum.duration': 'Dauer',
  'rv.sum.total': 'Geschätzt gesamt',
  'rv.sum.empty': 'Offen',

  'rv.back': 'Zurück',
  'rv.next': 'Weiter',
  'rv.confirm': 'Termin bestätigen',

  'rv.done.title': 'Anfrage gesendet!',
  'rv.done.text': 'Ihre Terminanfrage wurde an Eloïse übermittelt. Sie erhalten innerhalb von 24 Std. eine Bestätigung per E-Mail.',
  'rv.done.again': 'Weitere Buchung vornehmen',
  'rv.done.note': 'Demo — keine Online-Zahlung. Die Bezahlung erfolgt vor Ort.',
  'rv.done.cal': 'Zum Kalender hinzufügen',

  'rv.gift.badge': 'Gutschein',
  'rv.gift.note': 'Sie verschenken diese Sitzung. Geben Sie Ihre Daten an: Der Gutschein wird Ihnen zugeschickt.',

  'rv.alert.eyebrow': 'Termin-Alerts',
  'rv.alert.title': 'Werden Sie benachrichtigt, sobald ein Termin frei wird.',
  'rv.alert.text': 'Wählen Sie einen oder mehrere Orte: Ich schreibe Ihnen, sobald neue Termine in meinen Kalender kommen.',
  'rv.alert.loc': 'Zu beobachtende Orte',
  'rv.alert.email': 'Ihre E-Mail',
  'rv.alert.freq': 'Häufigkeit',
  'rv.alert.freq.instant': 'Bei jedem neuen Termin',
  'rv.alert.freq.weekly': 'Eine Zusammenfassung pro Woche',
  'rv.alert.submit': 'Alerts aktivieren',
  'rv.alert.done.title': 'Alerts aktiviert',
  'rv.alert.done.text': 'Notiert. Ich benachrichtige Sie, sobald ein Termin frei wird für:',
  'rv.alert.done.again': 'Alerts ändern',
  'rv.alert.pickloc': 'Bitte mindestens einen Ort wählen.',
});

Object.assign(window.I18N.en, {
  'rv.hero.eyebrow': 'Booking',
  'rv.hero.title': 'Book your session.',
  'rv.hero.text': 'Choose the treatment, location and time slot that suit you — it only takes a moment.',

  'rv.step.1': 'Treatment',
  'rv.step.2': 'Place & duration',
  'rv.step.3': 'Date & time',
  'rv.step.4': 'Your details',
  'rv.step.5': 'Confirmation',

  'rv.pack.cat': 'Offers & packs',
  'rv.pack.offerLabel': '{label} — {price}€ instead of {regular}€',
  'rv.pack.note': 'This offer will be confirmed with Eloïse — payment is on site.',
  'rv.pack.short': 'Offer',
  'rv.sum.discount': 'Discount',

  'rv.s1.title': 'Which treatment would you like?',
  'rv.s1.sub': 'Select a service to begin.',
  'rv.cat.massage': 'Massages',
  'rv.cat.drainage': 'Lymphatic drainage',
  'rv.cat.yoga': 'Yoga',

  'rv.s2.title': 'Where and how long?',
  'rv.s2.loc': 'Session location',
  'rv.s2.dur': 'Duration',
  'rv.s2.option': 'Option',
  'rv.min': 'min',
  'rv.h': 'h',

  'rv.s3.title': 'Choose your slot',
  'rv.s3.sub': 'Availability in',
  'rv.morning': 'Morning',
  'rv.afternoon': 'Afternoon',
  'rv.evening': 'Evening',
  'rv.noslots': 'Fully booked that day — try another date.',
  'rv.pickday': 'Pick a day to see the slots.',
  'rv.alert.inline': 'No date works? Get alerted about new slots',
  'rv.more': 'Show more dates',

  'rv.s4.title': 'Your details',
  'rv.s4.sub': 'To confirm and send you the details.',
  'rv.f.first': 'First name',
  'rv.f.last': 'Last name',
  'rv.f.email': 'Email',
  'rv.f.phone': 'Phone',
  'rv.f.notes': 'A word for Eloïse (optional)',
  'rv.f.notes.ph': 'A request, an area to ease, a first time…',
  'rv.f.consent': 'I agree to be contacted about this appointment.',
  'rv.req': 'This field is required',
  'rv.req.email': 'Invalid email address',

  'rv.summary': 'Summary',
  'rv.sum.service': 'Treatment',
  'rv.sum.loc': 'Location',
  'rv.sum.when': 'Date',
  'rv.sum.duration': 'Duration',
  'rv.sum.total': 'Estimated total',
  'rv.sum.empty': 'To complete',

  'rv.back': 'Back',
  'rv.next': 'Continue',
  'rv.confirm': 'Confirm appointment',

  'rv.done.title': 'Request sent!',
  'rv.done.text': 'Your appointment request has been sent to Eloïse. You will receive an email confirmation within 24 h.',
  'rv.done.again': 'Make another booking',
  'rv.done.note': 'Demo — no online payment. Payment is made on site.',
  'rv.done.cal': 'Add to my calendar',

  'rv.gift.badge': 'Gift card',
  'rv.gift.note': 'You are gifting this session. Enter your details: the gift card will be sent to you.',

  'rv.alert.eyebrow': 'Slot alerts',
  'rv.alert.title': 'Be notified the moment a slot opens.',
  'rv.alert.text': 'Target one or more locations: I’ll write to you as soon as new availability is added to my calendar.',
  'rv.alert.loc': 'Locations to watch',
  'rv.alert.email': 'Your email',
  'rv.alert.freq': 'Frequency',
  'rv.alert.freq.instant': 'Every new slot',
  'rv.alert.freq.weekly': 'A weekly summary',
  'rv.alert.submit': 'Activate my alerts',
  'rv.alert.done.title': 'Alerts activated',
  'rv.alert.done.text': 'Noted. I’ll let you know as soon as a slot opens for:',
  'rv.alert.done.again': 'Edit my alerts',
  'rv.alert.pickloc': 'Please choose at least one location.',
});
