/* strings-admin.js — i18n for newsletter cities, public modules (Instagram,
   upcoming dates) and the admin space. Augments window.I18N. Load AFTER
   strings-common.js. */
window.I18N = window.I18N || { fr: {}, de: {}, en: {} };

/* ----------------------------- FRANÇAIS ----------------------------- */
Object.assign(window.I18N.fr, {
  'meta.title.admin': 'Espace Eloïse — Administration',

  /* newsletter (footer) */
  'news.title2': 'Soyez prévenu·e de mes dates',
  'news.cities': 'Recevoir les dates à :',
  'news.name.ph': 'Votre prénom (facultatif)',
  'news.done2': 'Merci ! Vous serez prévenu·e des prochaines dates.',

  /* upcoming dates (public) */
  'dates.eyebrow': 'Agenda',
  'dates.title': 'Mes prochaines dates',
  'dates.text': 'Je me déplace selon les saisons. Voici mes prochaines disponibilités par ville.',
  'dates.book': 'Réserver',
  'dates.none': 'De nouvelles dates arrivent très bientôt. Inscrivez-vous pour être prévenu·e.',
  'dates.from': 'de',
  'dates.to': 'à',

  /* instagram (public) */
  'insta.eyebrow': 'Sur Instagram',
  'insta.title': 'Suivez le quotidien du studio',
  'insta.follow': 'Suivre @elo_aum',
  'insta.handle': '@elo_aum',

  /* leave a comment (public) */
  'rev.eyebrow': 'Votre avis',
  'rev.title': 'Partagez votre expérience',
  'rev.text': 'Votre témoignage compte. Il sera publié après lecture par Eloïse.',
  'rev.name': 'Votre prénom',
  'rev.city': 'Lieu de la séance',
  'rev.service': 'Soin reçu (facultatif)',
  'rev.msg': 'Votre message',
  'rev.send': 'Envoyer mon avis',
  'rev.thanks': 'Merci infiniment ! Votre avis a été transmis à Eloïse.',
  'rev.rating': 'Votre note',

  /* admin */
  'adm.title': 'Espace Eloïse',
  'adm.sub': 'Votre tableau de bord — dates, abonnés, avis et Instagram.',
  'adm.login.title': 'Espace privé',
  'adm.login.text': 'Entrez votre code d’accès pour gérer votre activité.',
  'adm.login.ph': 'Code d’accès',
  'adm.login.btn': 'Entrer',
  'adm.login.err': 'Code incorrect. Réessayez.',
  'adm.login.hint': 'Démonstration — code : ',
  'adm.logout': 'Quitter',
  'adm.proto': 'Prototype — les données sont enregistrées dans ce navigateur uniquement. L’envoi des e-mails s’ouvre dans votre messagerie.',

  'adm.tab.dates': 'Mes dates',
  'adm.tab.subs': 'Abonnés',
  'adm.tab.reviews': 'Avis',
  'adm.tab.insta': 'Instagram',

  /* dates tab */
  'adm.d.add': 'Ajouter une date',
  'adm.d.city': 'Ville',
  'adm.d.date': 'Date',
  'adm.d.start': 'De',
  'adm.d.end': 'À',
  'adm.d.service': 'Soin (facultatif)',
  'adm.d.note': 'Note interne (facultatif)',
  'adm.d.save': 'Ajouter la date',
  'adm.d.upcoming': 'Dates à venir',
  'adm.d.past': 'Dates passées',
  'adm.d.none': 'Aucune date pour l’instant.',
  'adm.d.notify': 'Prévenir les abonnés',
  'adm.d.notified': 'Abonnés prévenus',
  'adm.d.delete': 'Supprimer',
  'adm.d.match': 'abonné·e·s ont coché cette ville',

  /* notify modal */
  'adm.n.title': 'Prévenir les abonnés',
  'adm.n.recipients': 'Destinataires',
  'adm.n.subject': 'Objet',
  'adm.n.body': 'Message',
  'adm.n.open': 'Ouvrir dans ma messagerie',
  'adm.n.copy': 'Copier les adresses',
  'adm.n.copied': 'Adresses copiées !',
  'adm.n.mark': 'Marquer comme envoyé',
  'adm.n.cancel': 'Fermer',
  'adm.n.empty': 'Aucun abonné n’a coché cette ville pour le moment.',
  'adm.n.sent': 'Envoi enregistré.',
  'adm.n.defSubject': 'Nouvelle date à {city} le {date}',
  'adm.n.defBody': 'Bonjour,\n\nJe serai présente à {city} le {date}{time}. Au plaisir de vous accueillir pour un moment de bien-être.\n\nRéservez votre créneau : {url}\n\nÀ très bientôt,\nEloïse Werle',

  /* subscribers tab */
  'adm.s.total': 'abonnés au total',
  'adm.s.byCity': 'Par ville',
  'adm.s.name': 'Prénom',
  'adm.s.email': 'E-mail',
  'adm.s.cities': 'Villes',
  'adm.s.since': 'Inscrit·e le',
  'adm.s.copyCity': 'Copier les e-mails',
  'adm.s.none': 'Aucun abonné pour l’instant.',
  'adm.s.del': 'Retirer',

  /* reviews tab */
  'adm.r.pending': 'En attente',
  'adm.r.published': 'Publiés',
  'adm.r.none': 'Rien ici pour l’instant.',
  'adm.r.approve': 'Publier',
  'adm.r.unpublish': 'Dépublier',
  'adm.r.reject': 'Supprimer',
  'adm.r.add': 'Ajouter un avis',
  'adm.r.addBtn': 'Ajouter',
  'adm.r.empty': 'Le champ message est requis.',

  /* insta tab */
  'adm.i.add': 'Ajouter une publication',
  'adm.i.pick': 'Image',
  'adm.i.url': 'ou collez l’URL d’une image',
  'adm.i.caption': 'Légende',
  'adm.i.save': 'Publier',
  'adm.i.none': 'Aucune publication.',
  'adm.i.del': 'Retirer',
  'adm.i.hint': 'Ces images alimentent le bloc « Sur Instagram » de la page d’accueil.',

  'adm.footer.link': 'Espace Eloïse',

  'adm.tab.places': 'Lieux',
  'adm.p.add': 'Ajouter une ville',
  'adm.p.name': 'Nom de la ville',
  'adm.p.region': 'Région / Pays',
  'adm.p.map': 'Étiquette courte (ex. « Sucy · 94 »)',
  'adm.p.days': 'Jours de présence habituels',
  'adm.p.save': 'Ajouter la ville',
  'adm.p.list': 'Mes lieux',
  'adm.p.builtin': 'Par défaut',
  'adm.p.custom': 'Ajoutée',
  'adm.p.del': 'Supprimer',
  'adm.p.delconfirm': 'Supprimer ce lieu du site ?',
  'adm.p.hint': 'Les villes apparaissent automatiquement sur tout le site : accueil, « Où me trouver », agenda, pied de page et réservation.',
  'adm.p.nameReq': 'Le nom de la ville est requis.',
  'adm.p.none': 'Aucun lieu.',

  'adm.s.history': 'Historique',
  'adm.s.appts': 'rdv',
  'adm.h.title': 'Historique des rendez-vous',
  'adm.h.upcoming': 'À venir',
  'adm.h.past': 'Passés',
  'adm.h.none': 'Aucun rendez-vous enregistré pour ce contact.',
  'adm.h.close': 'Fermer',

  'news.cta.title': 'Vous souhaitez recevoir les prochaines dates dès leur parution ? Inscrivez-vous',
  'news.modal.title': 'Recevoir mes prochaines dates',
  'news.modal.text': 'Choisissez vos lieux : je vous écris dès qu’une nouvelle date est publiée.',

  'adm.p.edit': 'Modifier',
  'adm.p.editTitle': 'Modifier le lieu',
  'adm.p.save2': 'Enregistrer',
  'adm.p.active': 'Affiché sur le site',

  'adm.tab.soins': 'Mes soins',
  'adm.sv.add': 'Ajouter un soin',
  'adm.sv.name': 'Nom du soin',
  'adm.sv.tag': 'Description courte',
  'adm.sv.price': 'Prix (€)',
  'adm.sv.unit': 'Unité',
  'adm.sv.img': 'Photo',
  'adm.sv.url': 'ou collez l’URL d’une image',
  'adm.sv.save': 'Ajouter le soin',
  'adm.sv.list': 'Mes soins',
  'adm.sv.published': 'Publié sur l’accueil',
  'adm.sv.edit': 'Modifier',
  'adm.sv.del': 'Supprimer',
  'adm.sv.delconfirm': 'Supprimer ce soin ?',
  'adm.sv.editTitle': 'Modifier le soin',
  'adm.sv.saveEdit': 'Enregistrer',
  'adm.sv.hint': 'Les soins publiés apparaissent sur la page d’accueil. Les soins par défaut peuvent être modifiés ou dépubliés.',
  'adm.sv.nameReq': 'Le nom du soin est requis.',
  'adm.sv.none': 'Aucun soin.',
  'adm.sv.builtin': 'Par défaut',
  'adm.sv.custom': 'Ajouté'
});

/* ----------------------------- DEUTSCH ----------------------------- */
Object.assign(window.I18N.de, {
  'meta.title.admin': 'Eloïse-Bereich — Verwaltung',

  'news.title2': 'Erfahren Sie meine Termine',
  'news.cities': 'Termine erhalten für:',
  'news.name.ph': 'Ihr Vorname (optional)',
  'news.done2': 'Danke! Sie werden über die nächsten Termine informiert.',

  'dates.eyebrow': 'Kalender',
  'dates.title': 'Meine nächsten Termine',
  'dates.text': 'Ich reise je nach Saison. Hier meine nächsten Verfügbarkeiten pro Stadt.',
  'dates.book': 'Buchen',
  'dates.none': 'Neue Termine folgen in Kürze. Tragen Sie sich ein, um benachrichtigt zu werden.',
  'dates.from': 'von',
  'dates.to': 'bis',

  'insta.eyebrow': 'Auf Instagram',
  'insta.title': 'Folgen Sie dem Studio-Alltag',
  'insta.follow': '@elo_aum folgen',
  'insta.handle': '@elo_aum',

  'rev.eyebrow': 'Ihre Meinung',
  'rev.title': 'Teilen Sie Ihre Erfahrung',
  'rev.text': 'Ihre Stimme zählt. Sie wird nach Prüfung durch Eloïse veröffentlicht.',
  'rev.name': 'Ihr Vorname',
  'rev.city': 'Ort der Sitzung',
  'rev.service': 'Erhaltene Behandlung (optional)',
  'rev.msg': 'Ihre Nachricht',
  'rev.send': 'Bewertung senden',
  'rev.thanks': 'Herzlichen Dank! Ihre Bewertung wurde an Eloïse übermittelt.',
  'rev.rating': 'Ihre Bewertung',

  'adm.title': 'Eloïse-Bereich',
  'adm.sub': 'Ihr Dashboard — Termine, Abonnenten, Bewertungen und Instagram.',
  'adm.login.title': 'Privater Bereich',
  'adm.login.text': 'Geben Sie Ihren Zugangscode ein, um Ihre Aktivität zu verwalten.',
  'adm.login.ph': 'Zugangscode',
  'adm.login.btn': 'Eintreten',
  'adm.login.err': 'Falscher Code. Bitte erneut versuchen.',
  'adm.login.hint': 'Demo — Code: ',
  'adm.logout': 'Verlassen',
  'adm.proto': 'Prototyp — Daten werden nur in diesem Browser gespeichert. Der E-Mail-Versand öffnet Ihr Mailprogramm.',

  'adm.tab.dates': 'Termine',
  'adm.tab.subs': 'Abonnenten',
  'adm.tab.reviews': 'Bewertungen',
  'adm.tab.insta': 'Instagram',

  'adm.d.add': 'Termin hinzufügen',
  'adm.d.city': 'Stadt',
  'adm.d.date': 'Datum',
  'adm.d.start': 'Von',
  'adm.d.end': 'Bis',
  'adm.d.service': 'Behandlung (optional)',
  'adm.d.note': 'Interne Notiz (optional)',
  'adm.d.save': 'Termin hinzufügen',
  'adm.d.upcoming': 'Kommende Termine',
  'adm.d.past': 'Vergangene Termine',
  'adm.d.none': 'Noch keine Termine.',
  'adm.d.notify': 'Abonnenten benachrichtigen',
  'adm.d.notified': 'Abonnenten benachrichtigt',
  'adm.d.delete': 'Löschen',
  'adm.d.match': 'Abonnent·innen haben diese Stadt gewählt',

  'adm.n.title': 'Abonnenten benachrichtigen',
  'adm.n.recipients': 'Empfänger',
  'adm.n.subject': 'Betreff',
  'adm.n.body': 'Nachricht',
  'adm.n.open': 'Im Mailprogramm öffnen',
  'adm.n.copy': 'Adressen kopieren',
  'adm.n.copied': 'Adressen kopiert!',
  'adm.n.mark': 'Als gesendet markieren',
  'adm.n.cancel': 'Schließen',
  'adm.n.empty': 'Noch hat niemand diese Stadt gewählt.',
  'adm.n.sent': 'Versand gespeichert.',
  'adm.n.defSubject': 'Neuer Termin in {city} am {date}',
  'adm.n.defBody': 'Hallo,\n\nich bin am {date} in {city}{time}. Ich freue mich, Sie zu einem Moment des Wohlbefindens zu empfangen.\n\nBuchen Sie Ihren Termin: {url}\n\nBis bald,\nEloïse Werle',

  'adm.s.total': 'Abonnenten insgesamt',
  'adm.s.byCity': 'Nach Stadt',
  'adm.s.name': 'Vorname',
  'adm.s.email': 'E-Mail',
  'adm.s.cities': 'Städte',
  'adm.s.since': 'Angemeldet am',
  'adm.s.copyCity': 'E-Mails kopieren',
  'adm.s.none': 'Noch keine Abonnenten.',
  'adm.s.del': 'Entfernen',

  'adm.r.pending': 'Ausstehend',
  'adm.r.published': 'Veröffentlicht',
  'adm.r.none': 'Hier noch nichts.',
  'adm.r.approve': 'Veröffentlichen',
  'adm.r.unpublish': 'Zurückziehen',
  'adm.r.reject': 'Löschen',
  'adm.r.add': 'Bewertung hinzufügen',
  'adm.r.addBtn': 'Hinzufügen',
  'adm.r.empty': 'Das Nachrichtenfeld ist erforderlich.',

  'adm.i.add': 'Beitrag hinzufügen',
  'adm.i.pick': 'Bild',
  'adm.i.url': 'oder Bild-URL einfügen',
  'adm.i.caption': 'Bildunterschrift',
  'adm.i.save': 'Veröffentlichen',
  'adm.i.none': 'Keine Beiträge.',
  'adm.i.del': 'Entfernen',
  'adm.i.hint': 'Diese Bilder speisen den Block „Auf Instagram“ auf der Startseite.',

  'adm.footer.link': 'Eloïse-Bereich',

  'adm.tab.places': 'Orte',
  'adm.p.add': 'Ort hinzufügen',
  'adm.p.name': 'Name des Ortes',
  'adm.p.region': 'Region / Land',
  'adm.p.map': 'Kurzes Label (z. B. „Sucy · 94“)',
  'adm.p.days': 'Übliche Anwesenheitstage',
  'adm.p.save': 'Ort hinzufügen',
  'adm.p.list': 'Meine Orte',
  'adm.p.builtin': 'Standard',
  'adm.p.custom': 'Hinzugefügt',
  'adm.p.del': 'Löschen',
  'adm.p.delconfirm': 'Diesen Ort von der Website entfernen?',
  'adm.p.hint': 'Orte erscheinen automatisch auf der ganzen Website: Startseite, „Wo Sie mich finden“, Kalender, Fußzeile und Buchung.',
  'adm.p.nameReq': 'Der Name des Ortes ist erforderlich.',
  'adm.p.none': 'Keine Orte.',

  'adm.s.history': 'Verlauf',
  'adm.s.appts': 'Termine',
  'adm.h.title': 'Terminverlauf',
  'adm.h.upcoming': 'Bevorstehend',
  'adm.h.past': 'Vergangen',
  'adm.h.none': 'Keine Termine für diesen Kontakt gespeichert.',
  'adm.h.close': 'Schließen',

  'news.cta.title': 'Möchten Sie die nächsten Termine bei Veröffentlichung erhalten? Hier eintragen',
  'news.modal.title': 'Meine nächsten Termine erhalten',
  'news.modal.text': 'Wählen Sie Ihre Orte: Ich schreibe Ihnen, sobald ein neuer Termin veröffentlicht wird.',

  'adm.p.edit': 'Bearbeiten',
  'adm.p.editTitle': 'Ort bearbeiten',
  'adm.p.save2': 'Speichern',
  'adm.p.active': 'Auf der Website angezeigt',

  'adm.tab.soins': 'Behandlungen',
  'adm.sv.add': 'Behandlung hinzufügen',
  'adm.sv.name': 'Name der Behandlung',
  'adm.sv.tag': 'Kurzbeschreibung',
  'adm.sv.price': 'Preis (€)',
  'adm.sv.unit': 'Einheit',
  'adm.sv.img': 'Foto',
  'adm.sv.url': 'oder Bild-URL einfügen',
  'adm.sv.save': 'Behandlung hinzufügen',
  'adm.sv.list': 'Meine Behandlungen',
  'adm.sv.published': 'Auf der Startseite veröffentlicht',
  'adm.sv.edit': 'Bearbeiten',
  'adm.sv.del': 'Löschen',
  'adm.sv.delconfirm': 'Diese Behandlung löschen?',
  'adm.sv.editTitle': 'Behandlung bearbeiten',
  'adm.sv.saveEdit': 'Speichern',
  'adm.sv.hint': 'Veröffentlichte Behandlungen erscheinen auf der Startseite. Standardbehandlungen können bearbeitet oder zurückgezogen werden.',
  'adm.sv.nameReq': 'Der Name der Behandlung ist erforderlich.',
  'adm.sv.none': 'Keine Behandlungen.',
  'adm.sv.builtin': 'Standard',
  'adm.sv.custom': 'Hinzugefügt'
});

/* ----------------------------- ENGLISH ----------------------------- */
Object.assign(window.I18N.en, {
  'meta.title.admin': 'Eloïse Space — Admin',

  'news.title2': 'Hear about my upcoming dates',
  'news.cities': 'Get dates for:',
  'news.name.ph': 'Your first name (optional)',
  'news.done2': 'Thank you! You’ll hear about upcoming dates.',

  'dates.eyebrow': 'Calendar',
  'dates.title': 'My next dates',
  'dates.text': 'I travel with the seasons. Here are my next openings by city.',
  'dates.book': 'Book',
  'dates.none': 'New dates are coming soon. Subscribe to be notified.',
  'dates.from': 'from',
  'dates.to': 'to',

  'insta.eyebrow': 'On Instagram',
  'insta.title': 'Follow the studio’s daily life',
  'insta.follow': 'Follow @elo_aum',
  'insta.handle': '@elo_aum',

  'rev.eyebrow': 'Your feedback',
  'rev.title': 'Share your experience',
  'rev.text': 'Your voice matters. It will be published after Eloïse reads it.',
  'rev.name': 'Your first name',
  'rev.city': 'Session location',
  'rev.service': 'Treatment received (optional)',
  'rev.msg': 'Your message',
  'rev.send': 'Send my review',
  'rev.thanks': 'Thank you so much! Your review has been sent to Eloïse.',
  'rev.rating': 'Your rating',

  'adm.title': 'Eloïse Space',
  'adm.sub': 'Your dashboard — dates, subscribers, reviews and Instagram.',
  'adm.login.title': 'Private area',
  'adm.login.text': 'Enter your access code to manage your activity.',
  'adm.login.ph': 'Access code',
  'adm.login.btn': 'Enter',
  'adm.login.err': 'Wrong code. Try again.',
  'adm.login.hint': 'Demo — code: ',
  'adm.logout': 'Leave',
  'adm.proto': 'Prototype — data is stored in this browser only. Sending emails opens your mail app.',

  'adm.tab.dates': 'Dates',
  'adm.tab.subs': 'Subscribers',
  'adm.tab.reviews': 'Reviews',
  'adm.tab.insta': 'Instagram',

  'adm.d.add': 'Add a date',
  'adm.d.city': 'City',
  'adm.d.date': 'Date',
  'adm.d.start': 'From',
  'adm.d.end': 'To',
  'adm.d.service': 'Treatment (optional)',
  'adm.d.note': 'Internal note (optional)',
  'adm.d.save': 'Add date',
  'adm.d.upcoming': 'Upcoming dates',
  'adm.d.past': 'Past dates',
  'adm.d.none': 'No dates yet.',
  'adm.d.notify': 'Notify subscribers',
  'adm.d.notified': 'Subscribers notified',
  'adm.d.delete': 'Delete',
  'adm.d.match': 'subscribers chose this city',

  'adm.n.title': 'Notify subscribers',
  'adm.n.recipients': 'Recipients',
  'adm.n.subject': 'Subject',
  'adm.n.body': 'Message',
  'adm.n.open': 'Open in my mail app',
  'adm.n.copy': 'Copy addresses',
  'adm.n.copied': 'Addresses copied!',
  'adm.n.mark': 'Mark as sent',
  'adm.n.cancel': 'Close',
  'adm.n.empty': 'No subscriber has chosen this city yet.',
  'adm.n.sent': 'Send logged.',
  'adm.n.defSubject': 'New date in {city} on {date}',
  'adm.n.defBody': 'Hello,\n\nI’ll be in {city} on {date}{time}. I’d love to welcome you for a moment of wellbeing.\n\nBook your slot: {url}\n\nSee you soon,\nEloïse Werle',

  'adm.s.total': 'subscribers in total',
  'adm.s.byCity': 'By city',
  'adm.s.name': 'First name',
  'adm.s.email': 'Email',
  'adm.s.cities': 'Cities',
  'adm.s.since': 'Joined on',
  'adm.s.copyCity': 'Copy emails',
  'adm.s.none': 'No subscribers yet.',
  'adm.s.del': 'Remove',

  'adm.r.pending': 'Pending',
  'adm.r.published': 'Published',
  'adm.r.none': 'Nothing here yet.',
  'adm.r.approve': 'Publish',
  'adm.r.unpublish': 'Unpublish',
  'adm.r.reject': 'Delete',
  'adm.r.add': 'Add a review',
  'adm.r.addBtn': 'Add',
  'adm.r.empty': 'The message field is required.',

  'adm.i.add': 'Add a post',
  'adm.i.pick': 'Image',
  'adm.i.url': 'or paste an image URL',
  'adm.i.caption': 'Caption',
  'adm.i.save': 'Publish',
  'adm.i.none': 'No posts.',
  'adm.i.del': 'Remove',
  'adm.i.hint': 'These images feed the “On Instagram” block on the home page.',

  'adm.footer.link': 'Eloïse Space',

  'adm.tab.places': 'Locations',
  'adm.p.add': 'Add a location',
  'adm.p.name': 'City name',
  'adm.p.region': 'Region / Country',
  'adm.p.map': 'Short label (e.g. “Sucy · 94”)',
  'adm.p.days': 'Usual days present',
  'adm.p.save': 'Add location',
  'adm.p.list': 'My locations',
  'adm.p.builtin': 'Default',
  'adm.p.custom': 'Added',
  'adm.p.del': 'Delete',
  'adm.p.delconfirm': 'Remove this location from the site?',
  'adm.p.hint': 'Locations appear automatically across the site: home, “Where to find me”, calendar, footer and booking.',
  'adm.p.nameReq': 'City name is required.',
  'adm.p.none': 'No locations.',

  'adm.s.history': 'History',
  'adm.s.appts': 'appts',
  'adm.h.title': 'Appointment history',
  'adm.h.upcoming': 'Upcoming',
  'adm.h.past': 'Past',
  'adm.h.none': 'No appointments on record for this contact.',
  'adm.h.close': 'Close',

  'news.cta.title': 'Want to hear about new dates the moment they’re published? Sign up',
  'news.modal.title': 'Get my upcoming dates',
  'news.modal.text': 'Pick your locations: I’ll write to you as soon as a new date is published.',

  'adm.p.edit': 'Edit',
  'adm.p.editTitle': 'Edit location',
  'adm.p.save2': 'Save',
  'adm.p.active': 'Shown on the site',

  'adm.tab.soins': 'My treatments',
  'adm.sv.add': 'Add a treatment',
  'adm.sv.name': 'Treatment name',
  'adm.sv.tag': 'Short description',
  'adm.sv.price': 'Price (€)',
  'adm.sv.unit': 'Unit',
  'adm.sv.img': 'Photo',
  'adm.sv.url': 'or paste an image URL',
  'adm.sv.save': 'Add treatment',
  'adm.sv.list': 'My treatments',
  'adm.sv.published': 'Published on home',
  'adm.sv.edit': 'Edit',
  'adm.sv.del': 'Delete',
  'adm.sv.delconfirm': 'Delete this treatment?',
  'adm.sv.editTitle': 'Edit treatment',
  'adm.sv.saveEdit': 'Save',
  'adm.sv.hint': 'Published treatments appear on the home page. Default treatments can be edited or unpublished.',
  'adm.sv.nameReq': 'Treatment name is required.',
  'adm.sv.none': 'No treatments.',
  'adm.sv.builtin': 'Default',
  'adm.sv.custom': 'Added'
});
