/* Home page strings */
window.I18N = window.I18N || { fr: {}, de: {}, en: {} };

Object.assign(window.I18N.fr, {
  'home.hero.eyebrow': 'Massage & Yoga · France & Allemagne',
  'home.hero.title': 'Offrez-vous un moment de paix profonde.',
  'home.hero.title.em': 'paix profonde',
  'home.hero.text': 'Massages thérapeutiques et yoga personnalisé pour relâcher les tensions, faire circuler l’énergie et réharmoniser le corps et l’esprit.',
  'home.hero.scroll': 'Découvrir',

  'home.credo.kicker': 'Mon credo',
  'home.credo.quote': '« Une personne heureuse et en paix fait le bien autour d’elle. »',
  'home.credo.sign': 'Eloïse Werle',

  'home.intro.eyebrow': 'L’intention',
  'home.intro.title': 'Prendre soin de soi, c’est promouvoir sa santé.',
  'home.intro.text': 'Comprendre ses besoins, son corps et son esprit est essentiel pour développer de nouvelles habitudes qui viennent positivement impacter votre réalité. S’autoriser un massage, c’est s’offrir beaucoup d’amour et un système nerveux apaisé.',
  'home.intro.link': 'Mon parcours & mon approche',

  'home.serv.eyebrow': 'Les soins signature',
  'home.serv.title': 'Des massages choisis pour votre équilibre.',
  'home.serv.text': 'Chaque séance se construit autour de vos besoins du moment — détente profonde, circulation, mobilité.',

  'svc.thai.name': 'Thaï Yoga Massage',
  'svc.thai.tag': 'Étirements & énergie',
  'svc.bali.name': 'Massage Balinais',
  'svc.bali.tag': 'Enveloppant & circulatoire',
  'svc.deep.name': 'Deep Tissue',
  'svc.deep.tag': 'Tensions profondes',
  'svc.lymph.name': 'Drainage lymphatique',
  'svc.lymph.tag': 'Détox & légèreté',
  'svc.ayur.name': 'Ayurvédique & Abhyanga',
  'svc.ayur.tag': 'Chaleureux & nourrissant',
  'svc.yoga.name': 'Yoga personnalisé',
  'svc.yoga.tag': 'Mobilité & souffle',

  'home.approach.eyebrow': 'L’approche',
  'home.approach.title': 'Réharmoniser tous les corps qui nous composent.',
  'home.approach.text': 'Corps, esprit, émotions, énergie, subtil : retrouver l’équilibre entre eux, c’est vivre en parfaite symbiose et goûter à plus de sérénité.',
  'home.approach.b1.t': 'Le corps',
  'home.approach.b1.d': 'Relâcher les tensions physiques et redonner de la mobilité.',
  'home.approach.b2.t': 'Le système nerveux',
  'home.approach.b2.d': 'Apaiser le mode « combat-fuite » et réguler le cortisol.',
  'home.approach.b3.t': 'L’énergie',
  'home.approach.b3.d': 'Faire circuler les fluides et dissiper les blocages.',
  'home.approach.b4.t': 'L’esprit',
  'home.approach.b4.d': 'Un mental plus calme, des émotions apaisées.',

  'home.yoga.eyebrow': 'Yoga',
  'home.yoga.title': 'Une pratique sur mesure, dynamique ou plus douce.',
  'home.yoga.text': 'En privé ou en petit groupe, autour de la flexibilité, de la mobilité, du renforcement, de l’endurance et de la conscience corporelle — adaptée à vos capacités et à vos besoins.',
  'home.yoga.link': 'Découvrir le yoga',

  'home.places.eyebrow': 'Où me trouver',
  'home.places.title': 'Là où je vous accueille.',
  'home.places.text': 'Je reçois et me déplace selon les saisons. Choisissez votre lieu au moment de la réservation.',

  'home.testi.eyebrow': 'Elles témoignent',
  'home.testi.title': 'Des moments qui font du bien.',
  'testi.1.q': 'Une parenthèse hors du temps. Je suis repartie légère, le corps détendu et l’esprit clair. Les mains d’Eloïse sont d’une justesse rare.',
  'testi.1.n': 'Camille R.',
  'testi.1.r': 'Thaï Yoga Massage',
  'testi.2.q': 'Le drainage lymphatique a vraiment changé mon quotidien. Eloïse explique tout avec douceur et écoute le corps.',
  'testi.2.n': 'Sarah M.',
  'testi.2.r': 'Drainage lymphatique',
  'testi.3.q': 'Beaucoup de présence et de bienveillance. Mes cours de yoga sont devenus un vrai rituel de bien-être.',
  'testi.3.n': 'Léa B.',
  'testi.3.r': 'Yoga personnalisé',

  'home.gift.eyebrow': 'Carte-cadeau',
  'home.gift.title': 'Offrez un moment de bien-être.',
  'home.gift.text': 'Une carte-cadeau pour un massage ou une séance de yoga, valable un an dans tous mes lieux de pratique.',
  'home.gift.cta': 'Offrir une carte-cadeau',

  'home.cta.title': 'Prête à relâcher les tensions ?',
  'home.cta.text': 'Réservez votre séance en quelques instants — choisissez le soin, le lieu et le créneau qui vous conviennent.',
});

Object.assign(window.I18N.de, {
  'home.hero.eyebrow': 'Massage & Yoga · Frankreich & Deutschland',
  'home.hero.title': 'Schenken Sie sich einen Moment tiefen Friedens.',
  'home.hero.title.em': 'tiefen Friedens',
  'home.hero.text': 'Therapeutische Massagen und individuelles Yoga, um Spannungen zu lösen, Energie fließen zu lassen und Körper und Geist wieder in Einklang zu bringen.',
  'home.hero.scroll': 'Entdecken',

  'home.credo.kicker': 'Mein Credo',
  'home.credo.quote': '„Ein glücklicher und friedvoller Mensch tut Gutes um sich herum.“',
  'home.credo.sign': 'Eloïse Werle',

  'home.intro.eyebrow': 'Die Absicht',
  'home.intro.title': 'Für sich zu sorgen heißt, seine Gesundheit zu fördern.',
  'home.intro.text': 'Die eigenen Bedürfnisse, den Körper und den Geist zu verstehen, ist der Schlüssel zu neuen Gewohnheiten, die Ihren Alltag positiv verändern. Sich eine Massage zu gönnen heißt, sich viel Liebe und ein beruhigtes Nervensystem zu schenken.',
  'home.intro.link': 'Mein Weg & meine Haltung',

  'home.serv.eyebrow': 'Signatur-Behandlungen',
  'home.serv.title': 'Massagen, gewählt für Ihr Gleichgewicht.',
  'home.serv.text': 'Jede Sitzung richtet sich nach Ihren aktuellen Bedürfnissen — tiefe Entspannung, Durchblutung, Beweglichkeit.',

  'svc.thai.name': 'Thai-Yoga-Massage',
  'svc.thai.tag': 'Dehnung & Energie',
  'svc.bali.name': 'Balinesische Massage',
  'svc.bali.tag': 'Umhüllend & durchblutungsfördernd',
  'svc.deep.name': 'Deep Tissue',
  'svc.deep.tag': 'Tiefe Verspannungen',
  'svc.lymph.name': 'Lymphdrainage',
  'svc.lymph.tag': 'Entgiftung & Leichtigkeit',
  'svc.ayur.name': 'Ayurveda & Abhyanga',
  'svc.ayur.tag': 'Warm & nährend',
  'svc.yoga.name': 'Individuelles Yoga',
  'svc.yoga.tag': 'Beweglichkeit & Atem',

  'home.approach.eyebrow': 'Die Haltung',
  'home.approach.title': 'Alle Ebenen unseres Seins in Einklang bringen.',
  'home.approach.text': 'Körper, Geist, Emotionen, Energie, das Feinstoffliche: ihr Gleichgewicht wiederzufinden heißt, in vollkommener Symbiose zu leben und mehr Gelassenheit zu spüren.',
  'home.approach.b1.t': 'Der Körper',
  'home.approach.b1.d': 'Körperliche Spannungen lösen und Beweglichkeit zurückgeben.',
  'home.approach.b2.t': 'Das Nervensystem',
  'home.approach.b2.d': 'Den „Kampf-oder-Flucht“-Modus beruhigen und Cortisol regulieren.',
  'home.approach.b3.t': 'Die Energie',
  'home.approach.b3.d': 'Die Flüssigkeiten in Fluss bringen und Blockaden lösen.',
  'home.approach.b4.t': 'Der Geist',
  'home.approach.b4.d': 'Ein ruhigerer Geist, besänftigte Emotionen.',

  'home.yoga.eyebrow': 'Yoga',
  'home.yoga.title': 'Eine maßgeschneiderte Praxis, dynamisch oder sanfter.',
  'home.yoga.text': 'Privat oder in kleiner Gruppe — rund um Flexibilität, Beweglichkeit, Kräftigung, Ausdauer und Körperbewusstsein, abgestimmt auf Ihre Fähigkeiten und Bedürfnisse.',
  'home.yoga.link': 'Yoga entdecken',

  'home.places.eyebrow': 'Wo Sie mich finden',
  'home.places.title': 'Wo ich Sie empfange.',
  'home.places.text': 'Ich empfange und reise je nach Saison. Wählen Sie Ihren Ort bei der Buchung.',

  'home.testi.eyebrow': 'Stimmen',
  'home.testi.title': 'Momente, die guttun.',
  'testi.1.q': 'Eine Auszeit außerhalb der Zeit. Ich ging leicht, entspannt und mit klarem Geist. Eloïses Hände sind von seltener Genauigkeit.',
  'testi.1.n': 'Camille R.',
  'testi.1.r': 'Thai-Yoga-Massage',
  'testi.2.q': 'Die Lymphdrainage hat meinen Alltag wirklich verändert. Eloïse erklärt alles sanft und hört auf den Körper.',
  'testi.2.n': 'Sarah M.',
  'testi.2.r': 'Lymphdrainage',
  'testi.3.q': 'So viel Präsenz und Achtsamkeit. Meine Yogastunden sind zu einem echten Wohlfühl-Ritual geworden.',
  'testi.3.n': 'Léa B.',
  'testi.3.r': 'Individuelles Yoga',

  'home.gift.eyebrow': 'Gutschein',
  'home.gift.title': 'Verschenken Sie einen Moment des Wohlbefindens.',
  'home.gift.text': 'Ein Gutschein für eine Massage oder Yogastunde, ein Jahr lang an allen meinen Praxisorten gültig.',
  'home.gift.cta': 'Gutschein verschenken',

  'home.cta.title': 'Bereit, Spannungen loszulassen?',
  'home.cta.text': 'Buchen Sie Ihre Sitzung in wenigen Augenblicken — wählen Sie Behandlung, Ort und passenden Termin.',
});

Object.assign(window.I18N.en, {
  'home.hero.eyebrow': 'Massage & Yoga · France & Germany',
  'home.hero.title': 'Give yourself a moment of deep peace.',
  'home.hero.title.em': 'deep peace',
  'home.hero.text': 'Therapeutic massage and personalised yoga to release tension, let energy flow and bring body and mind back into harmony.',
  'home.hero.scroll': 'Discover',

  'home.credo.kicker': 'My credo',
  'home.credo.quote': '“A person who is happy and at peace does good all around them.”',
  'home.credo.sign': 'Eloïse Werle',

  'home.intro.eyebrow': 'The intention',
  'home.intro.title': 'Caring for yourself is nurturing your health.',
  'home.intro.text': 'Understanding your needs, your body and your mind is essential to building new habits that positively shape your daily life. Allowing yourself a massage is offering yourself plenty of love and a soothed nervous system.',
  'home.intro.link': 'My path & approach',

  'home.serv.eyebrow': 'Signature treatments',
  'home.serv.title': 'Massages chosen for your balance.',
  'home.serv.text': 'Each session is built around what you need right now — deep relaxation, circulation, mobility.',

  'svc.thai.name': 'Thai Yoga Massage',
  'svc.thai.tag': 'Stretching & energy',
  'svc.bali.name': 'Balinese Massage',
  'svc.bali.tag': 'Enveloping & circulatory',
  'svc.deep.name': 'Deep Tissue',
  'svc.deep.tag': 'Deep tension',
  'svc.lymph.name': 'Lymphatic drainage',
  'svc.lymph.tag': 'Detox & lightness',
  'svc.ayur.name': 'Ayurvedic & Abhyanga',
  'svc.ayur.tag': 'Warm & nourishing',
  'svc.yoga.name': 'Personalised yoga',
  'svc.yoga.tag': 'Mobility & breath',

  'home.approach.eyebrow': 'The approach',
  'home.approach.title': 'Bringing every layer of our being back into harmony.',
  'home.approach.text': 'Body, mind, emotions, energy, the subtle: finding their balance is to live in perfect symbiosis and taste more serenity.',
  'home.approach.b1.t': 'The body',
  'home.approach.b1.d': 'Release physical tension and restore mobility.',
  'home.approach.b2.t': 'The nervous system',
  'home.approach.b2.d': 'Soothe the “fight-or-flight” mode and regulate cortisol.',
  'home.approach.b3.t': 'Energy',
  'home.approach.b3.d': 'Let the fluids flow and clear blockages.',
  'home.approach.b4.t': 'The mind',
  'home.approach.b4.d': 'A calmer mind, soothed emotions.',

  'home.yoga.eyebrow': 'Yoga',
  'home.yoga.title': 'A tailored practice, dynamic or gentler.',
  'home.yoga.text': 'One-to-one or in a small group — around flexibility, mobility, strength, endurance and body awareness, adapted to your abilities and needs.',
  'home.yoga.link': 'Discover yoga',

  'home.places.eyebrow': 'Where to find me',
  'home.places.title': 'Where I welcome you.',
  'home.places.text': 'I welcome you and travel with the seasons. Choose your location when you book.',

  'home.testi.eyebrow': 'In their words',
  'home.testi.title': 'Moments that do you good.',
  'testi.1.q': 'A parenthesis outside of time. I left light, my body relaxed and my mind clear. Eloïse’s hands have a rare precision.',
  'testi.1.n': 'Camille R.',
  'testi.1.r': 'Thai Yoga Massage',
  'testi.2.q': 'The lymphatic drainage truly changed my daily life. Eloïse explains everything gently and listens to the body.',
  'testi.2.n': 'Sarah M.',
  'testi.2.r': 'Lymphatic drainage',
  'testi.3.q': 'So much presence and kindness. My yoga classes have become a real wellbeing ritual.',
  'testi.3.n': 'Léa B.',
  'testi.3.r': 'Personalised yoga',

  'home.gift.eyebrow': 'Gift card',
  'home.gift.title': 'Offer a moment of wellbeing.',
  'home.gift.text': 'A gift card for a massage or yoga session, valid for one year at all my practice locations.',
  'home.gift.cta': 'Give a gift card',

  'home.cta.title': 'Ready to release tension?',
  'home.cta.text': 'Book your session in moments — choose the treatment, location and time slot that suit you.',
});
