/* strings-admin.js — i18n for newsletter cities, public modules (Instagram,
   upcoming dates) and the admin space. Augments window.I18N. Load AFTER
   strings-common.js. */
window.I18N = window.I18N || { fr: {}, de: {}, en: {} };

/* ----------------------------- FRANÇAIS ----------------------------- */
Object.assign(window.I18N.fr, {
  'meta.title.admin': 'Espace Eloïse — Administration',

  /* newsletter (footer) */
  'news.title2': 'Soyez prévenu·e de mes dates',
  'news.cities': 'Recevoir les dates à :',
  'news.name.ph': 'Votre prénom (facultatif)',
  'news.done2': 'Merci ! Vous serez prévenu·e des prochaines dates.',

  /* upcoming dates (public) */
  'dates.eyebrow': 'Agenda',
  'dates.title': 'Mes prochaines dates',
  'dates.text': 'Je me déplace selon les saisons. Voici mes prochaines disponibilités par ville.',
  'dates.book': 'Réserver',
  'dates.none': 'De nouvelles dates arrivent très bientôt. Inscrivez-vous pour être prévenu·e.',
  'dates.from': 'de',
  'dates.to': 'à',
  'dates.more': 'Voir plus',
  'news.firstname.ph': 'Prénom',
  'news.lastname.ph': 'Nom',
  'adm.s.delcity': 'Retirer de cette ville',

  /* instagram (public) */
  'insta.eyebrow': 'Sur Instagram',
  'insta.title': 'Suivez le quotidien du studio',
  'insta.follow': 'Suivre @elo_aum',
  'insta.handle': '@elo_aum',

  /* leave a comment (public) */
  'rev.eyebrow': 'Votre avis',
  'rev.title': 'Partagez votre expérience',
  'rev.text': 'Votre témoignage compte. Il sera publié après lecture par Eloïse.',
  'rev.name': 'Votre prénom',
  'rev.city': 'Lieu de la séance',
  'rev.service': 'Soin reçu (facultatif)',
  'rev.msg': 'Votre message',
  'rev.send': 'Envoyer mon avis',
  'rev.thanks': 'Merci infiniment ! Votre avis a été transmis à Eloïse.',
  'rev.rating': 'Votre note',

  /* admin */
  'adm.title': 'Espace Eloïse',
  'adm.sub': 'Votre tableau de bord — dates, abonnés, avis et Instagram.',
  'adm.login.title': 'Espace privé',
  'adm.login.text': 'Entrez votre code d\'accès pour gérer votre activité.',
  'adm.login.ph': 'Code d\'accès',
  'adm.login.btn': 'Entrer',
  'adm.login.err': 'Code incorrect. Réessayez.',
  'adm.login.hint': 'Démonstration — code : ',
  'adm.login.forgot': 'Mot de passe oublié ?',
  'adm.reset.text': 'Entrez l\'adresse e-mail associée à ce compte pour réinitialiser votre code.',
  'adm.reset.newtext': 'Choisissez votre nouveau code d\'accès.',
  'adm.reset.verify': 'Vérifier',
  'adm.reset.save': 'Enregistrer le nouveau code',
  'adm.reset.ok': 'Code réinitialisé avec succès !',
  'adm.reset.back': 'Retour à la connexion',
  'adm.reset.err.email': 'Adresse e-mail invalide.',
  'adm.reset.err.nomatch': 'Adresse e-mail incorrecte.',
  'adm.sec.email.title': 'E-mail de récupération',
  'adm.sec.email.hint': 'Utilisé pour réinitialiser votre code d\'accès si vous l\'oubliez.',
  'adm.sec.email.label': 'Adresse e-mail',
  'adm.sec.email.ok': 'E-mail de récupération enregistré !',
  'adm.logout': 'Quitter',
  'adm.proto': 'Les données sont synchronisées en temps réel sur tous vos appareils.',

  'adm.tab.rdv': 'Rendez-vous',
  'adm.tab.dates': 'Mes dates',
  'adm.tab.subs': 'Abonnés',
  'adm.tab.reviews': 'Avis',
  'adm.tab.insta': 'Instagram',

  /* dates tab */
  'adm.d.add': 'Ajouter une date',
  'adm.d.city': 'Ville',
  'adm.d.date': 'Date',
  'adm.d.start': 'De',
  'adm.d.end': 'À',
  'adm.d.service': 'Soin (facultatif)',
  'adm.d.note': 'Note interne (facultatif)',
  'adm.d.save': 'Ajouter la date',
  'adm.d.upcoming': 'Dates à venir',
  'adm.d.past': 'Dates passées',
  'adm.d.none': 'Aucune date pour l\'instant.',
  'adm.d.notify': 'Prévenir les abonnés',
  'adm.d.notified': 'Abonnés prévenus',
  'adm.d.delete': 'Supprimer',
  'adm.d.match': 'abonné·e·s ont coché cette ville',

  /* notify modal */
  'adm.n.title': 'Prévenir les abonnés',
  'adm.n.recipients': 'Destinataires',
  'adm.n.subject': 'Objet',
  'adm.n.body': 'Message',
  'adm.n.open': 'Ouvrir dans ma messagerie',
  'adm.n.copy': 'Copier les adresses',
  'adm.n.copied': 'Adresses copiées !',
  'adm.n.mark': 'Marquer comme envoyé',
  'adm.n.cancel': 'Fermer',
  'adm.n.empty': 'Aucun abonné n\'a coché cette ville pour le moment.',
  'adm.n.sent': 'Envoi enregistré.',
  'adm.n.defSubject': 'Nouvelle date à {city} le {date}',
  'adm.n.defBody': 'Bonjour,\n\nJe serai présente à {city} le {date}{time}. Au plaisir de vous accueillir pour un moment de bien-être.\n\nRéservez votre créneau : {url}\n\nÀ très bientôt,\nEloïse Werle',

  /* subscribers tab */
  'adm.s.total': 'abonnés au total',
  'adm.s.byCity': 'Par ville',
  'adm.s.name': 'Prénom',
  'adm.s.email': 'E-mail',
  'adm.s.cities': 'Villes',
  'adm.s.since': 'Inscrit·e le',
  'adm.s.copyCity': 'Copier les e-mails',
  'adm.s.none': 'Aucun abonné pour l\'instant.',
  'adm.s.del': 'Retirer',

  /* reviews tab */
  'adm.r.pending': 'En attente',
  'adm.r.published': 'Publiés',
  'adm.r.none': 'Rien ici pour l\'instant.',
  'adm.r.approve': 'Publier',
  'adm.r.unpublish': 'Dépublier',
  'adm.r.reject': 'Supprimer',
  'adm.r.add': 'Ajouter un avis',
  'adm.r.addBtn': 'Ajouter',
  'adm.r.empty': 'Le champ message est requis.',

  /* insta tab */
  'adm.i.add': 'Ajouter une publication',
  'adm.i.pick': 'Image',
  'adm.i.url': 'ou collez l\'URL d\'une image',
  'adm.i.caption': 'Légende',
  'adm.i.save': 'Publier',
  'adm.i.none': 'Aucune publication.',
  'adm.i.del': 'Retirer',
  'adm.i.hint': 'Ces images alimentent le bloc « Sur Instagram » de la page d\'accueil.',

  'adm.footer.link': 'Espace Eloïse',

  'adm.tab.places': 'Lieux',
  'adm.p.add': 'Ajouter une ville',
  'adm.p.name': 'Nom de la ville',
  'adm.p.region': 'Région / Pays',
  'adm.p.map': 'Étiquette courte (ex. « Sucy · 94 »)',
  'adm.p.days': 'Jours de présence habituels',
  'adm.p.save': 'Ajouter la ville',
  'adm.p.list': 'Mes lieux',
  'adm.p.builtin': 'Par défaut',
  'adm.p.custom': 'Ajoutée',
  'adm.p.del': 'Supprimer',
  'adm.p.delconfirm': 'Supprimer ce lieu du site ?',
  'adm.p.hint': 'Les villes apparaissent automatiquement sur tout le site : accueil, « Où me trouver », agenda, pied de page et réservation.',
  'adm.p.nameReq': 'Le nom de la ville est requis.',
  'adm.p.none': 'Aucun lieu.',

  'adm.s.history': 'Historique',
  'adm.s.appts': 'rdv',
  'adm.h.title': 'Historique des rendez-vous',
  'adm.h.upcoming': 'À venir',
  'adm.h.past': 'Passés',
  'adm.h.none': 'Aucun rendez-vous enregistré pour ce contact.',
  'adm.h.close': 'Fermer',

  /* rendez-vous tab */
  'adm.rdv.total': 'Réservations',
  'adm.rdv.upcoming': 'À venir',
  'adm.rdv.past': 'Passés',
  'adm.rdv.none': 'Aucun rendez-vous pour le moment.',
  'adm.rdv.reply': 'Répondre',
  'adm.rdv.cancel': 'Annuler',
  'adm.rdv.cancelconfirm': 'Annuler ce rendez-vous ?',
  'adm.rdv.add': 'Ajouter un rendez-vous',
  'adm.rdv.client': 'Nom du client',
  'adm.rdv.save': 'Enregistrer',
  'adm.sv.durations': 'Durées & tarifs',
  'adm.sv.addDur': 'Ajouter une durée',
  'adm.sv.description': 'Description',
  'adm.sv.benefits': 'Bienfaits',
  'adm.sv.addBenefit': 'Ajouter un bienfait',
  'adm.sv.options': 'Variantes / options',
  'adm.sv.addOption': 'Ajouter une option',
  'adm.sv.benefitsPhysical': 'Bienfaits physiques',
  'adm.sv.benefitsEmotional': 'Bienfaits émotionnels & énergétiques',
  'adm.sv.idealFor': 'Idéal pour',
  'adm.sv.note': 'Note / À savoir',
  'adm.rdv.confirm': 'Confirmer',
  'adm.rdv.confirmed': 'Confirmé',
  'adm.rdv.confirmconfirm': 'Confirmer ce rendez-vous et envoyer l\'email de confirmation au client ?',
  'adm.rdv.confirmok': 'Rendez-vous confirmé !',
  'dates.filter.all': 'Toutes les villes',
  'adm.tab.securite': 'Sécurité',
  'adm.sec.pw.title': 'Modifier le mot de passe',
  'adm.sec.pw.current': 'Code actuel',
  'adm.sec.pw.new': 'Nouveau code',
  'adm.sec.pw.confirm': 'Confirmer le code',
  'adm.sec.pw.save': 'Enregistrer',
  'adm.sec.pw.err.wrong': 'Code actuel incorrect.',
  'adm.sec.pw.err.match': 'Les codes ne correspondent pas.',
  'adm.sec.pw.ok': 'Code modifié avec succès !',
  'adm.sec.sessions.title': 'Connexions récentes',
  'adm.sec.sessions.none': 'Aucune connexion enregistrée.',
  'adm.sec.disconnect': 'Déconnecter toutes les sessions',
  'adm.sec.disconnectconfirm': 'Déconnecter toutes les sessions et quitter ?',

  'news.cta.title': 'Vous souhaitez recevoir les prochaines dates dès leur parution ? Inscrivez-vous',
  'news.modal.title': 'Recevoir mes prochaines dates',
  'news.modal.text': 'Choisissez vos lieux : je vous écris dès qu\'une nouvelle date est publiée.',

  'adm.p.edit': 'Modifier',
  'adm.p.editTitle': 'Modifier le lieu',
  'adm.p.save2': 'Enregistrer',
  'adm.p.active': 'Affiché sur le site',

  'adm.tab.soins': 'Mes soins',
  'adm.sv.add': 'Ajouter un soin',
  'adm.sv.name': 'Nom du soin',
  'adm.sv.tag': 'Description courte',
  'adm.sv.category': 'Catégorie',
  'adm.sv.price': 'Prix (€)',
  'adm.sv.unit': 'Unité',
  'adm.sv.img': 'Photo',
  'adm.sv.url': 'ou collez l\'URL d\'une image',
  'adm.sv.save': 'Ajouter le soin',
  'adm.sv.list': 'Mes soins',
  'adm.sv.published': 'Publié sur l\'accueil',
  'adm.sv.edit': 'Modifier',
  'adm.sv.del': 'Supprimer',
  'adm.sv.delconfirm': 'Supprimer ce soin ?',
  'adm.sv.editTitle': 'Modifier le soin',
  'adm.sv.saveEdit': 'Enregistrer',
  'adm.sv.hint': 'Les soins publiés apparaissent sur la page d\'accueil. Les soins par défaut peuvent être modifiés ou dépubliés.',
  'adm.sv.nameReq': 'Le nom du soin est requis.',
  'adm.sv.none': 'Aucun soin.',
  'adm.sv.builtin': 'Par défaut',
  'adm.sv.custom': 'Ajouté',

  'adm.sv.benefitsPhysical': 'Bienfaits physiques',
  'adm.sv.benefitsEmotional': 'Bienfaits émotionnels & énergétiques',
  'adm.sv.idealFor': 'Idéal pour',
  'adm.sv.note': 'Note / À savoir',
  'adm.sv.translate': 'Traduire (DE/EN)',
  'adm.sv.translating': 'Traduction en cours…',
  'adm.sv.translateDone': 'Traduit ✓ — relisez et corrigez si besoin avant d\'enregistrer.',
  'adm.sv.translateError': 'Erreur de traduction.',
  'adm.sv.onePerLine': 'une ligne par bienfait',
  'adm.rdv.confirm': 'Confirmer',
  'adm.rdv.confirmed': 'Confirmé',
  'adm.rdv.confirmconfirm': 'Confirmer ce rendez-vous et envoyer l\'email au client ?',
  'adm.rdv.confirmok': 'Rendez-vous confirmé !'
});

/* ----------------------------- DEUTSCH ----------------------------- */
Object.assign(window.I18N.de, {
  'meta.title.admin': 'Eloïse-Bereich — Verwaltung',

  'news.title2': 'Erfahren Sie meine Termine',
  'news.cities': 'Termine erhalten für:',
  'news.name.ph': 'Ihr Vorname (optional)',
  'news.done2': 'Danke! Sie werden über die nächsten Termine informiert.',

  'dates.eyebrow': 'Kalender',
  'dates.title': 'Meine nächsten Termine',
  'dates.text': 'Ich reise je nach Saison. Hier meine nächsten Verfügbarkeiten pro Stadt.',
  'dates.book': 'Buchen',
  'dates.none': 'Neue Termine folgen in Kürze. Tragen Sie sich ein, um benachrichtigt zu werden.',
  'dates.from': 'von',
  'dates.to': 'bis',

  'insta.eyebrow': 'Auf Instagram',
  'insta.title': 'Folgen Sie dem Studio-Alltag',
  'insta.follow': '@elo_aum folgen',
  'insta.handle': '@elo_aum',

  'rev.eyebrow': 'Ihre Meinung',
  'rev.title': 'Teilen Sie Ihre Erfahrung',
  'rev.text': 'Ihre Stimme zählt. Sie wird nach Prüfung durch Eloïse veröffentlicht.',
  'rev.name': 'Ihr Vorname',
  'rev.city': 'Ort der Sitzung',
  'rev.service': 'Erhaltene Behandlung (optional)',
  'rev.msg': 'Ihre Nachricht',
  'rev.send': 'Bewertung senden',
  'rev.thanks': 'Herzlichen Dank! Ihre Bewertung wurde an Eloïse übermittelt.',
  'rev.rating': 'Ihre Bewertung',

  'adm.title': 'Eloïse-Bereich',
  'adm.sub': 'Ihr Dashboard — Termine, Abonnenten, Bewertungen und Instagram.',
  'adm.login.title': 'Privater Bereich',
  'adm.login.text': 'Geben Sie Ihren Zugangscode ein, um Ihre Aktivität zu verwalten.',
  'adm.login.ph': 'Zugangscode',
  'adm.login.btn': 'Eintreten',
  'adm.login.err': 'Falscher Code. Bitte erneut versuchen.',
  'adm.login.hint': 'Demo — Code: ',
  'adm.login.forgot': 'Passwort vergessen?',
  'adm.reset.text': 'Geben Sie die mit diesem Konto verknüpfte E-Mail-Adresse ein, um Ihren Code zurückzusetzen.',
  'adm.reset.newtext': 'Wählen Sie Ihren neuen Zugangscode.',
  'adm.reset.verify': 'Überprüfen',
  'adm.reset.save': 'Neuen Code speichern',
  'adm.reset.ok': 'Code erfolgreich zurückgesetzt!',
  'adm.reset.back': 'Zurück zur Anmeldung',
  'adm.reset.err.email': 'Ungültige E-Mail-Adresse.',
  'adm.reset.err.nomatch': 'E-Mail-Adresse falsch.',
  'adm.sec.email.title': 'Wiederherstellungs-E-Mail',
  'adm.sec.email.hint': 'Wird verwendet, um Ihren Zugangscode zurückzusetzen, falls Sie ihn vergessen.',
  'adm.sec.email.label': 'E-Mail-Adresse',
  'adm.sec.email.ok': 'Wiederherstellungs-E-Mail gespeichert!',
  'adm.logout': 'Verlassen',
  'adm.proto': 'Daten werden in Echtzeit auf allen Geräten synchronisiert.',

  'adm.tab.rdv': 'Termine',
  'adm.tab.dates': 'Termine',
  'adm.tab.subs': 'Abonnenten',
  'adm.tab.reviews': 'Bewertungen',
  'adm.tab.insta': 'Instagram',

  'adm.d.add': 'Termin hinzufügen',
  'adm.d.city': 'Stadt',
  'adm.d.date': 'Datum',
  'adm.d.start': 'Von',
  'adm.d.end': 'Bis',
  'adm.d.service': 'Behandlung (optional)',
  'adm.d.note': 'Interne Notiz (optional)',
  'adm.d.save': 'Termin hinzufügen',
  'adm.d.upcoming': 'Kommende Termine',
  'adm.d.past': 'Vergangene Termine',
  'adm.d.none': 'Noch keine Termine.',
  'adm.d.notify': 'Abonnenten benachrichtigen',
  'adm.d.notified': 'Abonnenten benachrichtigt',
  'adm.d.delete': 'Löschen',
  'adm.d.match': 'Abonnent·innen haben diese Stadt gewählt',

  'adm.n.title': 'Abonnenten benachrichtigen',
  'adm.n.recipients': 'Empfänger',
  'adm.n.subject': 'Betreff',
  'adm.n.body': 'Nachricht',
  'adm.n.open': 'Im Mailprogramm öffnen',
  'adm.n.copy': 'Adressen kopieren',
  'adm.n.copied': 'Adressen kopiert!',
  'adm.n.mark': 'Als gesendet markieren',
  'adm.n.cancel': 'Schließen',
  'adm.n.empty': 'Noch hat niemand diese Stadt gewählt.',
  'adm.n.sent': 'Versand gespeichert.',
  'adm.n.defSubject': 'Neuer Termin in {city} am {date}',
  'adm.n.defBody': 'Hallo,\n\nich bin am {date} in {city}{time}. Ich freue mich, Sie zu einem Moment des Wohlbefindens zu empfangen.\n\nBuchen Sie Ihren Termin: {url}\n\nBis bald,\nEloïse Werle',

  'adm.s.total': 'Abonnenten insgesamt',
  'adm.s.byCity': 'Nach Stadt',
  'adm.s.name': 'Vorname',
  'adm.s.email': 'E-Mail',
  'adm.s.cities': 'Städte',
  'adm.s.since': 'Angemeldet am',
  'adm.s.copyCity': 'E-Mails kopieren',
  'adm.s.none': 'Noch keine Abonnenten.',
  'adm.s.del': 'Entfernen',
  'adm.s.delcity': 'Von dieser Stadt entfernen',

  'adm.r.pending': 'Ausstehend',
  'adm.r.published': 'Veröffentlicht',
  'adm.r.none': 'Hier noch nichts.',
  'adm.r.approve': 'Veröffentlichen',
  'adm.r.unpublish': 'Zurückziehen',
  'adm.r.reject': 'Löschen',
  'adm.r.add': 'Bewertung hinzufügen',
  'adm.r.addBtn': 'Hinzufügen',
  'adm.r.empty': 'Das Nachrichtenfeld ist erforderlich.',

  'adm.i.add': 'Beitrag hinzufügen',
  'adm.i.pick': 'Bild',
  'adm.i.url': 'oder Bild-URL einfügen',
  'adm.i.caption': 'Bildunterschrift',
  'adm.i.save': 'Veröffentlichen',
  'adm.i.none': 'Keine Beiträge.',
  'adm.i.del': 'Entfernen',
  'adm.i.hint': 'Diese Bilder speisen den Block „Auf Instagram“ auf der Startseite.',

  'adm.footer.link': 'Eloïse-Bereich',

  'adm.tab.places': 'Orte',
  'adm.p.add': 'Ort hinzufügen',
  'adm.p.name': 'Name des Ortes',
  'adm.p.region': 'Region / Land',
  'adm.p.map': 'Kurzes Label (z. B. „Sucy · 94“)',
  'adm.p.days': 'Übliche Anwesenheitstage',
  'adm.p.save': 'Ort hinzufügen',
  'adm.p.list': 'Meine Orte',
  'adm.p.builtin': 'Standard',
  'adm.p.custom': 'Hinzugefügt',
  'adm.p.del': 'Löschen',
  'adm.p.delconfirm': 'Diesen Ort von der Website entfernen?',
  'adm.p.hint': 'Orte erscheinen automatisch auf der ganzen Website: Startseite, „Wo Sie mich finden“, Kalender, Fußzeile und Buchung.',
  'adm.p.nameReq': 'Der Name des Ortes ist erforderlich.',
  'adm.p.none': 'Keine Orte.',

  'adm.s.history': 'Verlauf',
  'adm.s.appts': 'Termine',
  'adm.h.title': 'Terminverlauf',
  'adm.h.upcoming': 'Bevorstehend',
  'adm.h.past': 'Vergangen',
  'adm.h.none': 'Keine Termine für diesen Kontakt gespeichert.',
  'adm.h.close': 'Schließen',

  /* rendez-vous tab */
  'adm.rdv.total': 'Buchungen',
  'adm.rdv.upcoming': 'Bevorstehend',
  'adm.rdv.past': 'Vergangen',
  'adm.rdv.none': 'Noch keine Termine.',
  'adm.rdv.reply': 'Antworten',
  'adm.rdv.cancel': 'Stornieren',
  'adm.rdv.cancelconfirm': 'Diesen Termin stornieren?',
  'adm.rdv.add': 'Termin hinzufügen',
  'adm.rdv.client': 'Kundenname',
  'adm.rdv.save': 'Speichern',
  'adm.sv.durations': 'Dauer & Preise',
  'adm.sv.addDur': 'Dauer hinzufügen',
  'adm.sv.description': 'Beschreibung',
  'adm.sv.benefits': 'Wirkung',
  'adm.sv.addBenefit': 'Wirkung hinzufügen',
  'adm.sv.options': 'Varianten / Optionen',
  'adm.sv.addOption': 'Option hinzufügen',
  'adm.sv.benefitsPhysical': 'Körperliche Vorteile',
  'adm.sv.benefitsEmotional': 'Emotionale & energetische Vorteile',
  'adm.sv.idealFor': 'Ideal für',
  'adm.sv.note': 'Hinweis',
  'adm.rdv.confirm': 'Bestätigen',
  'adm.rdv.confirmed': 'Bestätigt',
  'adm.rdv.confirmconfirm': 'Diesen Termin bestätigen und Bestätigungs-E-Mail senden?',
  'adm.rdv.confirmok': 'Termin bestätigt!',
  'dates.filter.all': 'Alle Städte',
  'adm.tab.securite': 'Sicherheit',
  'adm.sec.pw.title': 'Passwort ändern',
  'adm.sec.pw.current': 'Aktueller Code',
  'adm.sec.pw.new': 'Neuer Code',
  'adm.sec.pw.confirm': 'Code bestätigen',
  'adm.sec.pw.save': 'Speichern',
  'adm.sec.pw.err.wrong': 'Aktueller Code falsch.',
  'adm.sec.pw.err.match': 'Codes stimmen nicht überein.',
  'adm.sec.pw.ok': 'Code erfolgreich geändert!',
  'adm.sec.sessions.title': 'Letzte Anmeldungen',
  'adm.sec.sessions.none': 'Keine Anmeldungen aufgezeichnet.',
  'adm.sec.disconnect': 'Alle Sitzungen abmelden',
  'adm.sec.disconnectconfirm': 'Alle Sitzungen abmelden und abmelden?',

  'news.cta.title': 'Möchten Sie die nächsten Termine bei Veröffentlichung erhalten? Hier eintragen',
  'news.modal.title': 'Meine nächsten Termine erhalten',
  'news.modal.text': 'Wählen Sie Ihre Orte: Ich schreibe Ihnen, sobald ein neuer Termin veröffentlicht wird.',

  'adm.p.edit': 'Bearbeiten',
  'adm.p.editTitle': 'Ort bearbeiten',
  'adm.p.save2': 'Speichern',
  'adm.p.active': 'Auf der Website angezeigt',

  'adm.tab.soins': 'Behandlungen',
  'adm.sv.add': 'Behandlung hinzufügen',
  'adm.sv.name': 'Name der Behandlung',
  'adm.sv.tag': 'Kurzbeschreibung',
  'adm.sv.category': 'Kategorie',
  'adm.sv.price': 'Preis (€)',
  'adm.sv.unit': 'Einheit',
  'adm.sv.img': 'Foto',
  'adm.sv.url': 'oder Bild-URL einfügen',
  'adm.sv.save': 'Behandlung hinzufügen',
  'adm.sv.list': 'Meine Behandlungen',
  'adm.sv.published': 'Auf der Startseite veröffentlicht',
  'adm.sv.edit': 'Bearbeiten',
  'adm.sv.del': 'Löschen',
  'adm.sv.delconfirm': 'Diese Behandlung löschen?',
  'adm.sv.editTitle': 'Behandlung bearbeiten',
  'adm.sv.saveEdit': 'Speichern',
  'adm.sv.hint': 'Veröffentlichte Behandlungen erscheinen auf der Startseite. Standardbehandlungen können bearbeitet oder zurückgezogen werden.',
  'adm.sv.nameReq': 'Der Name der Behandlung ist erforderlich.',
  'adm.sv.none': 'Keine Behandlungen.',
  'adm.sv.builtin': 'Standard',
  'adm.sv.custom': 'Hinzugefügt',

  'adm.sv.benefitsPhysical': 'Körperliche Vorteile',
  'adm.sv.benefitsEmotional': 'Emotionale Vorteile',
  'adm.sv.idealFor': 'Ideal für',
  'adm.sv.note': 'Hinweis',
  'adm.sv.translate': 'Übersetzen (DE/EN)',
  'adm.sv.translating': 'Übersetzung läuft…',
  'adm.sv.translateDone': 'Übersetzt ✓ — vor dem Speichern bitte prüfen und ggf. korrigieren.',
  'adm.sv.translateError': 'Übersetzungsfehler.',
  'adm.sv.onePerLine': 'eine Zeile pro Vorteil',
  'adm.rdv.confirm': 'Bestätigen',
  'adm.rdv.confirmed': 'Bestätigt',
  'adm.rdv.confirmconfirm': 'Diesen Termin bestätigen?',
  'adm.rdv.confirmok': 'Termin bestätigt!'
});

/* ----------------------------- ENGLISH ----------------------------- */
Object.assign(window.I18N.en, {
  'meta.title.admin': 'Eloïse Space — Admin',

  'news.title2': 'Hear about my upcoming dates',
  'news.cities': 'Get dates for:',
  'news.name.ph': 'Your first name (optional)',
  'news.done2': 'Thank you! You\'ll hear about upcoming dates.',

  'dates.eyebrow': 'Calendar',
  'dates.title': 'My next dates',
  'dates.text': 'I travel with the seasons. Here are my next openings by city.',
  'dates.book': 'Book',
  'dates.none': 'New dates are coming soon. Subscribe to be notified.',
  'dates.from': 'from',
  'dates.to': 'to',

  'insta.eyebrow': 'On Instagram',
  'insta.title': 'Follow the studio\'s daily life',
  'insta.follow': 'Follow @elo_aum',
  'insta.handle': '@elo_aum',

  'rev.eyebrow': 'Your feedback',
  'rev.title': 'Share your experience',
  'rev.text': 'Your voice matters. It will be published after Eloïse reads it.',
  'rev.name': 'Your first name',
  'rev.city': 'Session location',
  'rev.service': 'Treatment received (optional)',
  'rev.msg': 'Your message',
  'rev.send': 'Send my review',
  'rev.thanks': 'Thank you so much! Your review has been sent to Eloïse.',
  'rev.rating': 'Your rating',

  'adm.title': 'Eloïse Space',
  'adm.sub': 'Your dashboard — dates, subscribers, reviews and Instagram.',
  'adm.login.title': 'Private area',
  'adm.login.text': 'Enter your access code to manage your activity.',
  'adm.login.ph': 'Access code',
  'adm.login.btn': 'Enter',
  'adm.login.err': 'Wrong code. Try again.',
  'adm.login.hint': 'Demo — code: ',
  'adm.login.forgot': 'Forgot password?',
  'adm.reset.text': 'Enter the email address linked to this account to reset your code.',
  'adm.reset.newtext': 'Choose your new access code.',
  'adm.reset.verify': 'Verify',
  'adm.reset.save': 'Save new code',
  'adm.reset.ok': 'Code successfully reset!',
  'adm.reset.back': 'Back to login',
  'adm.reset.err.email': 'Invalid email address.',
  'adm.reset.err.nomatch': 'Email address not recognised.',
  'adm.sec.email.title': 'Recovery email',
  'adm.sec.email.hint': 'Used to reset your access code if you forget it.',
  'adm.sec.email.label': 'Email address',
  'adm.sec.email.ok': 'Recovery email saved!',
  'adm.logout': 'Leave',
  'adm.proto': 'Data is synchronised in real time across all your devices.',

  'adm.tab.rdv': 'Appointments',
  'adm.tab.dates': 'Dates',
  'adm.tab.subs': 'Subscribers',
  'adm.tab.reviews': 'Reviews',
  'adm.tab.insta': 'Instagram',

  'adm.d.add': 'Add a date',
  'adm.d.city': 'City',
  'adm.d.date': 'Date',
  'adm.d.start': 'From',
  'adm.d.end': 'To',
  'adm.d.service': 'Treatment (optional)',
  'adm.d.note': 'Internal note (optional)',
  'adm.d.save': 'Add date',
  'adm.d.upcoming': 'Upcoming dates',
  'adm.d.past': 'Past dates',
  'adm.d.none': 'No dates yet.',
  'adm.d.notify': 'Notify subscribers',
  'adm.d.notified': 'Subscribers notified',
  'adm.d.delete': 'Delete',
  'adm.d.match': 'subscribers chose this city',

  'adm.n.title': 'Notify subscribers',
  'adm.n.recipients': 'Recipients',
  'adm.n.subject': 'Subject',
  'adm.n.body': 'Message',
  'adm.n.open': 'Open in my mail app',
  'adm.n.copy': 'Copy addresses',
  'adm.n.copied': 'Addresses copied!',
  'adm.n.mark': 'Mark as sent',
  'adm.n.cancel': 'Close',
  'adm.n.empty': 'No subscriber has chosen this city yet.',
  'adm.n.sent': 'Send logged.',
  'adm.n.defSubject': 'New date in {city} on {date}',
  'adm.n.defBody': 'Hello,\n\nI\'ll be in {city} on {date}{time}. I\'d love to welcome you for a moment of wellbeing.\n\nBook your slot: {url}\n\nSee you soon,\nEloïse Werle',

  'adm.s.total': 'subscribers in total',
  'adm.s.byCity': 'By city',
  'adm.s.name': 'First name',
  'adm.s.email': 'Email',
  'adm.s.cities': 'Cities',
  'adm.s.since': 'Joined on',
  'adm.s.copyCity': 'Copy emails',
  'adm.s.none': 'No subscribers yet.',
  'adm.s.del': 'Remove',

  'adm.s.delcity': 'Remove from this city',
  'adm.r.pending': 'Pending',
  'adm.r.published': 'Published',
  'adm.r.none': 'Nothing here yet.',
  'adm.r.approve': 'Publish',
  'adm.r.unpublish': 'Unpublish',
  'adm.r.reject': 'Delete',
  'adm.r.add': 'Add a review',
  'adm.r.addBtn': 'Add',
  'adm.r.empty': 'The message field is required.',

  'adm.i.add': 'Add a post',
  'adm.i.pick': 'Image',
  'adm.i.url': 'or paste an image URL',
  'adm.i.caption': 'Caption',
  'adm.i.save': 'Publish',
  'adm.i.none': 'No posts.',
  'adm.i.del': 'Remove',
  'adm.i.hint': 'These images feed the “On Instagram” block on the home page.',

  'adm.footer.link': 'Eloïse Space',

  'adm.tab.places': 'Locations',
  'adm.p.add': 'Add a location',
  'adm.p.name': 'City name',
  'adm.p.region': 'Region / Country',
  'adm.p.map': 'Short label (e.g. “Sucy · 94”)',
  'adm.p.days': 'Usual days present',
  'adm.p.save': 'Add location',
  'adm.p.list': 'My locations',
  'adm.p.builtin': 'Default',
  'adm.p.custom': 'Added',
  'adm.p.del': 'Delete',
  'adm.p.delconfirm': 'Remove this location from the site?',
  'adm.p.hint': 'Locations appear automatically across the site: home, “Where to find me”, calendar, footer and booking.',
  'adm.p.nameReq': 'City name is required.',
  'adm.p.none': 'No locations.',

  'adm.s.history': 'History',
  'adm.s.appts': 'appts',
  'adm.h.title': 'Appointment history',
  'adm.h.upcoming': 'Upcoming',
  'adm.h.past': 'Past',
  'adm.h.none': 'No appointments on record for this contact.',
  'adm.h.close': 'Close',

  /* rendez-vous tab */
  'adm.rdv.total': 'Bookings',
  'adm.rdv.upcoming': 'Upcoming',
  'adm.rdv.past': 'Past',
  'adm.rdv.none': 'No appointments yet.',
  'adm.rdv.reply': 'Reply',
  'adm.rdv.cancel': 'Cancel',
  'adm.rdv.cancelconfirm': 'Cancel this appointment?',
  'adm.rdv.add': 'Add an appointment',
  'adm.rdv.client': 'Client name',
  'adm.rdv.save': 'Save',
  'adm.sv.durations': 'Durations & prices',
  'adm.sv.addDur': 'Add duration',
  'adm.sv.description': 'Description',
  'adm.sv.benefits': 'Benefits',
  'adm.sv.addBenefit': 'Add benefit',
  'adm.sv.options': 'Variants / options',
  'adm.sv.addOption': 'Add option',
  'adm.sv.benefitsPhysical': 'Physical benefits',
  'adm.sv.benefitsEmotional': 'Emotional & energetic benefits',
  'adm.sv.idealFor': 'Ideal for',
  'adm.sv.note': 'Note',
  'adm.rdv.confirm': 'Confirm',
  'adm.rdv.confirmed': 'Confirmed',
  'adm.rdv.confirmconfirm': 'Confirm this appointment and send confirmation email to client?',
  'adm.rdv.confirmok': 'Appointment confirmed!',
  'dates.filter.all': 'All cities',
  'adm.tab.securite': 'Security',
  'adm.sec.pw.title': 'Change password',
  'adm.sec.pw.current': 'Current code',
  'adm.sec.pw.new': 'New code',
  'adm.sec.pw.confirm': 'Confirm code',
  'adm.sec.pw.save': 'Save',
  'adm.sec.pw.err.wrong': 'Current code is incorrect.',
  'adm.sec.pw.err.match': 'Codes do not match.',
  'adm.sec.pw.ok': 'Code successfully changed!',
  'adm.sec.sessions.title': 'Recent logins',
  'adm.sec.sessions.none': 'No logins recorded yet.',
  'adm.sec.disconnect': 'Disconnect all sessions',
  'adm.sec.disconnectconfirm': 'Disconnect all sessions and log out?',

  'news.cta.title': 'Want to hear about new dates the moment they\'re published? Sign up',
  'news.modal.title': 'Get my upcoming dates',
  'news.modal.text': 'Pick your locations: I\'ll write to you as soon as a new date is published.',

  'adm.p.edit': 'Edit',
  'adm.p.editTitle': 'Edit location',
  'adm.p.save2': 'Save',
  'adm.p.active': 'Shown on the site',

  'adm.tab.soins': 'My treatments',
  'adm.sv.add': 'Add a treatment',
  'adm.sv.name': 'Treatment name',
  'adm.sv.tag': 'Short description',
  'adm.sv.category': 'Category',
  'adm.sv.price': 'Price (€)',
  'adm.sv.unit': 'Unit',
  'adm.sv.img': 'Photo',
  'adm.sv.url': 'or paste an image URL',
  'adm.sv.save': 'Add treatment',
  'adm.sv.list': 'My treatments',
  'adm.sv.published': 'Published on home',
  'adm.sv.edit': 'Edit',
  'adm.sv.del': 'Delete',
  'adm.sv.delconfirm': 'Delete this treatment?',
  'adm.sv.editTitle': 'Edit treatment',
  'adm.sv.saveEdit': 'Save',
  'adm.sv.hint': 'Published treatments appear on the home page. Default treatments can be edited or unpublished.',
  'adm.sv.nameReq': 'Treatment name is required.',
  'adm.sv.none': 'No treatments.',
  'adm.sv.builtin': 'Default',
  'adm.sv.custom': 'Added',
  'adm.sv.translate': 'Translate (DE/EN)',
  'adm.sv.translating': 'Translating…',
  'adm.sv.translateDone': 'Translated ✓ — review and correct before saving.',
  'adm.sv.translateError': 'Translation error.',
  'adm.sv.onePerLine': 'one line per benefit'
});
