/* strings-legal.js — legal notice & privacy policy (FR / DE / EN). Augments window.I18N. */
window.I18N = window.I18N || { fr: {}, de: {}, en: {} };
Object.assign(window.I18N.fr, {
  "lgm.1": "Mentions légales",
  "lgm.2": "← Retour à l'accueil",
  "lgm.3": "1. Éditeur du site",
  "lgm.4": "Eloïse Werle<br>\n      Email : <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a><br>\n      Téléphone : <a href=\"tel:+33608044818\">+33 6 08 04 48 18</a>",
  "lgm.5": "2. Responsable de la publication",
  "lgm.6": "Eloïse Werle",
  "lgm.7": "3. Hébergeur",
  "lgm.8": "Vercel Inc.<br>\n      440 N Barranca Ave #4133, Covina, CA 91723, États-Unis<br>\n      <a href=\"https://vercel.com\" target=\"_blank\" rel=\"noopener\">vercel.com</a>",
  "lgm.9": "4. Propriété intellectuelle",
  "lgm.10": "L'ensemble du contenu de ce site (textes, images, logos, vidéos, structure) est protégé par le droit d'auteur. Toute reproduction, représentation, modification ou adaptation, totale ou partielle, est interdite sans autorisation préalable écrite.",
  "lgm.11": "5. Limitation de responsabilité",
  "lgm.12": "Les informations contenues sur ce site sont fournies à titre indicatif. Eloïse Werle ne saurait être tenue responsable des erreurs ou omissions, ni des résultats obtenus par l'utilisation de ces informations.",
  "lgm.13": "6. Liens externes",
  "lgm.14": "Ce site peut contenir des liens vers des sites externes. Eloïse Werle n'exerce aucun contrôle sur ces sites et décline toute responsabilité quant à leur contenu.",
  "lgm.15": "7. Droit applicable",
  "lgm.16": "Le présent site est soumis au droit français. En cas de litige, les tribunaux français seront seuls compétents.",
  "lgm.17": "8. Contact",
  "lgm.18": "Pour toute question concernant ces mentions légales :<br>\n      <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a>",
  "lgm.19": "9. Création du site",
  "lgm.20": "Pour toute question concernant le site :<br>\n      <a href=\"mailto:lise.werle@gmail.com\">lise.werle@gmail.com</a>",
  "lgp.1": "Politique de confidentialité",
  "lgp.2": "Dernière mise à jour : 07/06/2026",
  "lgp.3": "← Retour à l'accueil",
  "lgp.4": "1. Responsable du traitement",
  "lgp.5": "Eloïse Werle<br>\n      Email : <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a><br>\n      Site web : <a href=\"https://eloisewerle.com\">eloisewerle.com</a>",
  "lgp.6": "2. Données collectées",
  "lgp.7": "Nous collectons les données suivantes :",
  "lgp.8": "<strong>Formulaire de contact :</strong> nom, prénom, email, téléphone, message",
  "lgp.9": "<strong>Formulaire de réservation :</strong> nom, prénom, email, soin souhaité, lieu, date",
  "lgp.10": "<strong>Données de navigation :</strong> stockage de session technique essentiel",
  "lgp.11": "3. Finalités du traitement",
  "lgp.12": "Vos données sont utilisées pour :",
  "lgp.13": "Répondre à vos demandes de contact",
  "lgp.14": "Gérer les réservations des soins (confirmer, déplacer, annuler)",
  "lgp.15": "Assurer le bon fonctionnement du site",
  "lgp.16": "4. Base légale",
  "lgp.17": "Le traitement de vos données est fondé sur :",
  "lgp.18": "<strong>Votre consentement</strong> (formulaires de contact)",
  "lgp.19": "<strong>L'exécution d'un contrat</strong> (réservation d'un soin)",
  "lgp.20": "<strong>Notre intérêt légitime</strong> (amélioration du site)",
  "lgp.21": "5. Durée de conservation",
  "lgp.22": "<strong>Données de contact :</strong> 3 ans après le dernier échange",
  "lgp.23": "<strong>Cookies :</strong> 13 mois maximum",
  "lgp.24": "6. Vos droits",
  "lgp.25": "Conformément au RGPD, vous disposez des droits suivants :",
  "lgp.26": "<strong>Droit d'accès :</strong> obtenir une copie de vos données",
  "lgp.27": "<strong>Droit de rectification :</strong> corriger vos données",
  "lgp.28": "<strong>Droit à l'effacement :</strong> supprimer vos données",
  "lgp.29": "<strong>Droit à la portabilité :</strong> récupérer vos données",
  "lgp.30": "<strong>Droit d'opposition :</strong> vous opposer au traitement",
  "lgp.31": "Pour exercer vos droits : <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a>",
  "lgp.32": "7. Sécurité",
  "lgp.33": "Nous mettons en œuvre des mesures techniques et organisationnelles pour protéger vos données :",
  "lgp.34": "<strong>Chiffrement des communications</strong> — le site est servi exclusivement en HTTPS/TLS via Vercel",
  "lgp.35": "Protection des formulaires",
  "lgp.36": "Mots de passe chiffrés",
  "lgp.37": "8. Cookies et stockage local",
  "lgp.38": "Ce site utilise uniquement un stockage de session technique :",
  "lgp.39": "<strong>Stockage de session :</strong> maintien de la connexion à l'espace Eloïse (expiré à la fermeture du navigateur)",
  "lgp.40": "<strong>Stockage local :</strong> préférences de langue et données de fonctionnement du site",
  "lgp.41": "Aucun cookie de tracking, publicitaire ou tiers (Meta, Google…) n'est utilisé. Les images du bloc Instagram sont gérées manuellement et ne proviennent pas d'une intégration directe avec Meta.",
  "lgp.42": "9. Réclamation",
  "lgp.43": "Vous pouvez introduire une réclamation auprès de la CNIL :<br>\n      <a href=\"https://www.cnil.fr\" target=\"_blank\" rel=\"noopener\">www.cnil.fr</a>",
});
Object.assign(window.I18N.de, {
  "lgm.1": "Impressum",
  "lgm.2": "← Zurück zur Startseite",
  "lgm.3": "1. Herausgabe der Website",
  "lgm.4": "Eloïse Werle<br>\n      E-Mail: <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a><br>\n      Telefon: <a href=\"tel:+33608044818\">+33 6 08 04 48 18</a>",
  "lgm.5": "2. Verantwortlich für den Inhalt",
  "lgm.6": "Eloïse Werle",
  "lgm.7": "3. Hosting",
  "lgm.8": "Vercel Inc.<br>\n      440 N Barranca Ave #4133, Covina, CA 91723, USA<br>\n      <a href=\"https://vercel.com\" target=\"_blank\" rel=\"noopener\">vercel.com</a>",
  "lgm.9": "4. Geistiges Eigentum",
  "lgm.10": "Alle Inhalte dieser Website (Texte, Bilder, Logos, Videos, Struktur) sind urheberrechtlich geschützt. Jede vollständige oder teilweise Vervielfältigung, Darstellung, Änderung oder Bearbeitung ist ohne vorherige schriftliche Genehmigung untersagt.",
  "lgm.11": "5. Haftungsbeschränkung",
  "lgm.12": "Die Informationen auf dieser Website dienen nur zur Orientierung. Eloïse Werle haftet weder für Fehler oder Auslassungen noch für Ergebnisse, die durch die Nutzung dieser Informationen erzielt werden.",
  "lgm.13": "6. Externe Links",
  "lgm.14": "Diese Website kann Links zu externen Websites enthalten. Eloïse Werle hat keinen Einfluss auf diese Websites und übernimmt keine Verantwortung für deren Inhalte.",
  "lgm.15": "7. Anwendbares Recht",
  "lgm.16": "Diese Website unterliegt französischem Recht. Bei Streitigkeiten sind ausschließlich die französischen Gerichte zuständig.",
  "lgm.17": "8. Kontakt",
  "lgm.18": "Bei Fragen zu diesem Impressum:<br>\n      <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a>",
  "lgm.19": "9. Erstellung der Website",
  "lgm.20": "Bei Fragen zur Website:<br>\n      <a href=\"mailto:lise.werle@gmail.com\">lise.werle@gmail.com</a>",
  "lgp.1": "Datenschutzerklärung",
  "lgp.2": "Zuletzt aktualisiert: 07.06.2026",
  "lgp.3": "← Zurück zur Startseite",
  "lgp.4": "1. Verantwortliche Stelle",
  "lgp.5": "Eloïse Werle<br>\n      E-Mail: <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a><br>\n      Website: <a href=\"https://eloisewerle.com\">eloisewerle.com</a>",
  "lgp.6": "2. Erhobene Daten",
  "lgp.7": "Wir erheben folgende Daten:",
  "lgp.8": "<strong>Kontaktformular:</strong> Name, Vorname, E-Mail, Telefon, Nachricht",
  "lgp.9": "<strong>Buchungsformular:</strong> Name, Vorname, E-Mail, gewünschte Behandlung, Ort, Datum",
  "lgp.10": "<strong>Nutzungsdaten:</strong> technisch notwendige Sitzungsspeicherung",
  "lgp.11": "3. Zwecke der Verarbeitung",
  "lgp.12": "Ihre Daten werden verwendet, um:",
  "lgp.13": "Ihre Kontaktanfragen zu beantworten",
  "lgp.14": "Buchungen von Behandlungen zu verwalten (bestätigen, verschieben, stornieren)",
  "lgp.15": "den ordnungsgemäßen Betrieb der Website sicherzustellen",
  "lgp.16": "4. Rechtsgrundlage",
  "lgp.17": "Die Verarbeitung Ihrer Daten beruht auf:",
  "lgp.18": "<strong>Ihrer Einwilligung</strong> (Kontaktformulare)",
  "lgp.19": "<strong>der Erfüllung eines Vertrags</strong> (Buchung einer Behandlung)",
  "lgp.20": "<strong>unserem berechtigten Interesse</strong> (Verbesserung der Website)",
  "lgp.21": "5. Speicherdauer",
  "lgp.22": "<strong>Kontaktdaten:</strong> 3 Jahre nach dem letzten Austausch",
  "lgp.23": "<strong>Cookies:</strong> höchstens 13 Monate",
  "lgp.24": "6. Ihre Rechte",
  "lgp.25": "Gemäß der DSGVO haben Sie folgende Rechte:",
  "lgp.26": "<strong>Auskunftsrecht:</strong> eine Kopie Ihrer Daten erhalten",
  "lgp.27": "<strong>Recht auf Berichtigung:</strong> Ihre Daten korrigieren",
  "lgp.28": "<strong>Recht auf Löschung:</strong> Ihre Daten löschen",
  "lgp.29": "<strong>Recht auf Datenübertragbarkeit:</strong> Ihre Daten erhalten",
  "lgp.30": "<strong>Widerspruchsrecht:</strong> der Verarbeitung widersprechen",
  "lgp.31": "Zur Ausübung Ihrer Rechte: <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a>",
  "lgp.32": "7. Sicherheit",
  "lgp.33": "Wir treffen technische und organisatorische Maßnahmen zum Schutz Ihrer Daten:",
  "lgp.34": "<strong>Verschlüsselte Übertragung</strong> — die Website wird ausschließlich über HTTPS/TLS via Vercel ausgeliefert",
  "lgp.35": "Schutz der Formulare",
  "lgp.36": "Verschlüsselte Passwörter",
  "lgp.37": "8. Cookies und lokale Speicherung",
  "lgp.38": "Diese Website verwendet ausschließlich technische Speicherung:",
  "lgp.39": "<strong>Sitzungsspeicher:</strong> hält die Anmeldung im Bereich „Espace Eloïse“ aufrecht (endet beim Schließen des Browsers)",
  "lgp.40": "<strong>Lokaler Speicher:</strong> Spracheinstellungen und Betriebsdaten der Website",
  "lgp.41": "Es werden keine Tracking-, Werbe- oder Drittanbieter-Cookies (Meta, Google …) verwendet. Die Bilder im Instagram-Bereich werden manuell gepflegt und stammen nicht aus einer direkten Einbindung von Meta.",
  "lgp.42": "9. Beschwerde",
  "lgp.43": "Sie können eine Beschwerde bei der CNIL (französische Datenschutzbehörde) einreichen:<br>\n      <a href=\"https://www.cnil.fr\" target=\"_blank\" rel=\"noopener\">www.cnil.fr</a>",
});
Object.assign(window.I18N.en, {
  "lgm.1": "Legal notice",
  "lgm.2": "← Back to home",
  "lgm.3": "1. Website publisher",
  "lgm.4": "Eloïse Werle<br>\n      Email: <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a><br>\n      Phone: <a href=\"tel:+33608044818\">+33 6 08 04 48 18</a>",
  "lgm.5": "2. Publication manager",
  "lgm.6": "Eloïse Werle",
  "lgm.7": "3. Hosting provider",
  "lgm.8": "Vercel Inc.<br>\n      440 N Barranca Ave #4133, Covina, CA 91723, United States<br>\n      <a href=\"https://vercel.com\" target=\"_blank\" rel=\"noopener\">vercel.com</a>",
  "lgm.9": "4. Intellectual property",
  "lgm.10": "All content on this website (texts, images, logos, videos, structure) is protected by copyright. Any full or partial reproduction, representation, modification or adaptation is prohibited without prior written permission.",
  "lgm.11": "5. Limitation of liability",
  "lgm.12": "The information on this website is provided for guidance only. Eloïse Werle cannot be held liable for any errors or omissions, nor for any results obtained from using this information.",
  "lgm.13": "6. External links",
  "lgm.14": "This website may contain links to external websites. Eloïse Werle has no control over these websites and accepts no responsibility for their content.",
  "lgm.15": "7. Applicable law",
  "lgm.16": "This website is governed by French law. In the event of a dispute, the French courts shall have exclusive jurisdiction.",
  "lgm.17": "8. Contact",
  "lgm.18": "For any questions about this legal notice:<br>\n      <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a>",
  "lgm.19": "9. Website creation",
  "lgm.20": "For any questions about the website:<br>\n      <a href=\"mailto:lise.werle@gmail.com\">lise.werle@gmail.com</a>",
  "lgp.1": "Privacy policy",
  "lgp.2": "Last updated: 07/06/2026",
  "lgp.3": "← Back to home",
  "lgp.4": "1. Data controller",
  "lgp.5": "Eloïse Werle<br>\n      Email: <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a><br>\n      Website: <a href=\"https://eloisewerle.com\">eloisewerle.com</a>",
  "lgp.6": "2. Data collected",
  "lgp.7": "We collect the following data:",
  "lgp.8": "<strong>Contact form:</strong> last name, first name, email, phone, message",
  "lgp.9": "<strong>Booking form:</strong> last name, first name, email, requested treatment, location, date",
  "lgp.10": "<strong>Browsing data:</strong> essential technical session storage",
  "lgp.11": "3. Purposes of processing",
  "lgp.12": "Your data is used to:",
  "lgp.13": "Respond to your contact requests",
  "lgp.14": "Manage treatment bookings (confirm, reschedule, cancel)",
  "lgp.15": "Ensure the website works properly",
  "lgp.16": "4. Legal basis",
  "lgp.17": "The processing of your data is based on:",
  "lgp.18": "<strong>Your consent</strong> (contact forms)",
  "lgp.19": "<strong>The performance of a contract</strong> (booking a treatment)",
  "lgp.20": "<strong>Our legitimate interest</strong> (improving the website)",
  "lgp.21": "5. Retention period",
  "lgp.22": "<strong>Contact data:</strong> 3 years after the last exchange",
  "lgp.23": "<strong>Cookies:</strong> 13 months maximum",
  "lgp.24": "6. Your rights",
  "lgp.25": "Under the GDPR, you have the following rights:",
  "lgp.26": "<strong>Right of access:</strong> obtain a copy of your data",
  "lgp.27": "<strong>Right to rectification:</strong> correct your data",
  "lgp.28": "<strong>Right to erasure:</strong> delete your data",
  "lgp.29": "<strong>Right to data portability:</strong> retrieve your data",
  "lgp.30": "<strong>Right to object:</strong> object to the processing",
  "lgp.31": "To exercise your rights: <a href=\"mailto:eloiserose.werle@gmail.com\">eloiserose.werle@gmail.com</a>",
  "lgp.32": "7. Security",
  "lgp.33": "We implement technical and organisational measures to protect your data:",
  "lgp.34": "<strong>Encrypted communications</strong> — the website is served exclusively over HTTPS/TLS via Vercel",
  "lgp.35": "Form protection",
  "lgp.36": "Encrypted passwords",
  "lgp.37": "8. Cookies and local storage",
  "lgp.38": "This website only uses technical storage:",
  "lgp.39": "<strong>Session storage:</strong> keeps you signed in to the Eloïse area (cleared when the browser is closed)",
  "lgp.40": "<strong>Local storage:</strong> language preferences and website operating data",
  "lgp.41": "No tracking, advertising or third-party cookies (Meta, Google…) are used. The images in the Instagram section are managed manually and do not come from a direct integration with Meta.",
  "lgp.42": "9. Complaints",
  "lgp.43": "You can lodge a complaint with the CNIL (French data protection authority):<br>\n      <a href=\"https://www.cnil.fr\" target=\"_blank\" rel=\"noopener\">www.cnil.fr</a>",
});
